-- Migrace na nové schéma, jen pokud už nebyla provedena
IF(
	(SELECT COUNT(Culture) FROM LiteralLookup WHERE LiteralGroup=0 AND LiteralValue=0) = 1 AND
	(SELECT TOP 1 Culture FROM LiteralLookup WHERE LiteralGroup=0 AND LiteralValue=0)=''
  ) DELETE FROM LiteralLookup

EXEC DefineLiteralLookup 0, 0, 'cs-CZ', N'LiteralLookupGroup', N'Překladová tabulka - Skupina'

EXEC DefineLiteralLookup 0, 20, 'cs-CZ', N'WorkflowEvent_EventType', N'Událost pracovního postupu - Typ'
EXEC DefineLiteralLookup 20, 0, 'cs-CZ', N'Start', N'Začátek'
EXEC DefineLiteralLookup 20, 1, 'cs-CZ', N'End', N'Konec'
EXEC DefineLiteralLookup 20, 2, 'cs-CZ', N'Resume', N'Pokračovat'
EXEC DefineLiteralLookup 20, 3, 'cs-CZ', N'Pause', N'Pozastavit'
EXEC DefineLiteralLookup 20, 10, 'cs-CZ', N'StepSucceeded', N'Krok uspěl'
EXEC DefineLiteralLookup 20, 20, 'cs-CZ', N'StepFailed', N'Krok selhal'
EXEC DefineLiteralLookup 20, 21, 'cs-CZ', N'StepTimeOut', N'Krok se vyčasoval'
EXEC DefineLiteralLookup 20, 30, 'cs-CZ', N'StepSkipNoTime', N'Krok přeskočen (časová podmínka)'
EXEC DefineLiteralLookup 20, 31, 'cs-CZ', N'StepForkedOut', N'Krok ukončen paralelním procesem'
EXEC DefineLiteralLookup 20, 32, 'cs-CZ', N'StepResultedOut', N'Krok ukončen po zadání výsledku'
EXEC DefineLiteralLookup 20, 40, 'cs-CZ', N'InfiniteLoop', N'Nekonečná smyčka'
EXEC DefineLiteralLookup 20, 50, 'cs-CZ', N'MessageRequested', N'Podána výzva zprávou'
EXEC DefineLiteralLookup 20, 51, 'cs-CZ', N'MessageSent', N'Odeslána výzva zprávou'
EXEC DefineLiteralLookup 20, 52, 'cs-CZ', N'MessageResponded', N'Obdržena odpověď na výzvu zprávou'
EXEC DefineLiteralLookup 20, 55, 'cs-CZ', N'CallRequested', N'Podána výzva hovorem'
EXEC DefineLiteralLookup 20, 56, 'cs-CZ', N'CallMade', N'Provedena výzva hovorem'
EXEC DefineLiteralLookup 20, 57, 'cs-CZ', N'CallResponded', N'Obdržena odpověď na výzvu hovorem'
EXEC DefineLiteralLookup 20, 60, 'cs-CZ', N'NoPagingData', N'Neexistují data pro svolávání'
EXEC DefineLiteralLookup 20, 61, 'cs-CZ', N'ManualCancel', N'Manuální zrušení svolávání'
EXEC DefineLiteralLookup 20, 80, 'cs-CZ', N'ScenarioResultCreated', N'Vytvořena sada formulářových dat'
EXEC DefineLiteralLookup 20, 90, 'cs-CZ', N'Triggered', N'Spoušť WF'
EXEC DefineLiteralLookup 20, 91, 'cs-CZ', N'TriggeredSql', N'Spoušť SQL'
EXEC DefineLiteralLookup 20, 99, 'cs-CZ', N'TriggerSuspended', N'Spoušť pozasatvena'

EXEC DefineLiteralLookup 0, 21, 'cs-CZ', N'WorkflowInstance_Activity', N'Běh pracovního postupu - Aktivita'
EXEC DefineLiteralLookup 21, 0, 'cs-CZ', N'New', N'Nový'
EXEC DefineLiteralLookup 21, 1, 'cs-CZ', N'Active', N'Běžící'
EXEC DefineLiteralLookup 21, 5, 'cs-CZ', N'Paused', N'Pozastavený'
EXEC DefineLiteralLookup 21, 10, 'cs-CZ', N'Succeeded', N'Uspěl'
EXEC DefineLiteralLookup 21, 20, 'cs-CZ', N'Failed', N'Selhal'
EXEC DefineLiteralLookup 21, 21, 'cs-CZ', N'TimeOut', N'Vyčasování'
EXEC DefineLiteralLookup 21, 30, 'cs-CZ', N'Canceled', N'Zrušený'

EXEC DefineLiteralLookup 0, 30, 'cs-CZ', N'Agent_Activity', N'Agent - Aktivita'
EXEC DefineLiteralLookup 30, 0, 'cs-CZ', N'Ready', N'Připraven'
EXEC DefineLiteralLookup 30, 1, 'cs-CZ', N'Pause', N'Přestávka'
EXEC DefineLiteralLookup 30, 2, 'cs-CZ', N'PostCall', N'Zpracování'
EXEC DefineLiteralLookup 30, 3, 'cs-CZ', N'Logoff', N'Odhlášen'

EXEC DefineLiteralLookup 0, 31, 'cs-CZ', N'AgentEvent_EventType', N'Událost agenta - Typ'
EXEC DefineLiteralLookup 31, 0, 'cs-CZ', N'AgentStatus', N'Změna stavu'
EXEC DefineLiteralLookup 31, 1, 'cs-CZ', N'AgentWarn', N'Upozornění automatu'
EXEC DefineLiteralLookup 31, 2, 'cs-CZ', N'AgentProjectChannel', N'Zapojení do projektu'
EXEC DefineLiteralLookup 31, 3, 'cs-CZ', N'AgentProjectEnable', N'Povolení projektu'
EXEC DefineLiteralLookup 31, 4, 'cs-CZ', N'AgentError', N'Chyba'
EXEC DefineLiteralLookup 31, 5, 'cs-CZ', N'AgentCorrelation', N'Změna režimu'
EXEC DefineLiteralLookup 31, 6, 'cs-CZ', N'AgentInternalChat', N'Interní chat'

EXEC DefineLiteralLookup 0, 35, 'cs-CZ', N'Workplace_Offer', N'Pracoviště - Nabídka hovoru'
EXEC DefineLiteralLookup 35, 0, 'cs-CZ', N'None', N'Žádná akce'
EXEC DefineLiteralLookup 35, 1, 'cs-CZ', N'Pending', N'Čeká se výsledek'
EXEC DefineLiteralLookup 35, 2, 'cs-CZ', N'Offering', N'Nabízím hovor'

EXEC DefineLiteralLookup 0, 36, 'cs-CZ', N'Workplace_State', N'Pracoviště - Stav'
EXEC DefineLiteralLookup 36, 0, 'cs-CZ', N'Free', N'Volno'
EXEC DefineLiteralLookup 36, 1, 'cs-CZ', N'Busy', N'Obsazeno'
EXEC DefineLiteralLookup 36, 2, 'cs-CZ', N'Ring', N'Zvonění'
EXEC DefineLiteralLookup 36, 3, 'cs-CZ', N'Hold', N'Odloženo'
EXEC DefineLiteralLookup 36, 4, 'cs-CZ', N'Transfer', N'Přepojení'
EXEC DefineLiteralLookup 36, 5, 'cs-CZ', N'OutOfOrder', N'Porucha'

EXEC DefineLiteralLookup 0, 40, 'cs-CZ', N'InboundCall_CallResult', N'Příchozí hovor - Výsledek zpracování'
EXEC DefineLiteralLookup 40, 0, 'cs-CZ', N'Active', N'Aktivní'
EXEC DefineLiteralLookup 40, 1, 'cs-CZ', N'Lost', N'Ztracený'
EXEC DefineLiteralLookup 40, 2, 'cs-CZ', N'Served', N'Obsloužený'

EXEC DefineLiteralLookup 0, 41, 'cs-CZ', N'InboundCall_CallPhase', N'Příchozí hovor - Fáze zpracování'
EXEC DefineLiteralLookup 41, 0, 'cs-CZ', N'AgentRingFirst', N'První zvonění'
EXEC DefineLiteralLookup 41, 1, 'cs-CZ', N'AgentRingMissed', N'Zmeškané zvonění'
EXEC DefineLiteralLookup 41, 2, 'cs-CZ', N'AgentRingNext', N'Další zvonění'
EXEC DefineLiteralLookup 41, 3, 'cs-CZ', N'AgentTalk', N'Hovor'
EXEC DefineLiteralLookup 41, 4, 'cs-CZ', N'AnnouncementA', N'Hláska A'
EXEC DefineLiteralLookup 41, 5, 'cs-CZ', N'AnnouncementB', N'Hláska B'
EXEC DefineLiteralLookup 41, 6, 'cs-CZ', N'AnnouncementW', N'Hláska čekací'
EXEC DefineLiteralLookup 41, 7, 'cs-CZ', N'DispatchQueue', N'Manuální čekací fronta'
EXEC DefineLiteralLookup 41, 8, 'cs-CZ', N'Enqueue', N'Distribuce'
EXEC DefineLiteralLookup 41, 9, 'cs-CZ', N'HangupAgent', N'Zavěsil agent'
EXEC DefineLiteralLookup 41, 10, 'cs-CZ', N'HangupCaller', N'Zavěsil volající'
EXEC DefineLiteralLookup 41, 11, 'cs-CZ', N'IvrScriptA', N'IVR A'
EXEC DefineLiteralLookup 41, 12, 'cs-CZ', N'IvrScriptB', N'IVR B'
EXEC DefineLiteralLookup 41, 13, 'cs-CZ', N'IvrScriptW', N'IVR čekací'
EXEC DefineLiteralLookup 41, 14, 'cs-CZ', N'ManualDispatch', N'Manuální distribuce'
EXEC DefineLiteralLookup 41, 15, 'cs-CZ', N'New', N'Nový'
EXEC DefineLiteralLookup 41, 16, 'cs-CZ', N'Pilot', N'Vstup'
EXEC DefineLiteralLookup 41, 17, 'cs-CZ', N'TerminatedA', N'Ukončení A'
EXEC DefineLiteralLookup 41, 18, 'cs-CZ', N'TerminatedB', N'Ukončení B'
EXEC DefineLiteralLookup 41, 19, 'cs-CZ', N'TerminatedW', N'Ukončení čekací'
EXEC DefineLiteralLookup 41, 20, 'cs-CZ', N'TransferredA', N'Přepojení A'
EXEC DefineLiteralLookup 41, 21, 'cs-CZ', N'TransferredB', N'Přepojení B'
EXEC DefineLiteralLookup 41, 22, 'cs-CZ', N'TransferredW', N'Přepojení čekací'
EXEC DefineLiteralLookup 41, 23, 'cs-CZ', N'WaitingQueue', N'Čekací fronta'

EXEC DefineLiteralLookup 0, 42, 'cs-CZ', N'OutboundCall_CallResult', N'Odchozí hovor - Výsledek zpracování'
EXEC DefineLiteralLookup 42, 0, 'cs-CZ', N'Active', N'Aktivní'
EXEC DefineLiteralLookup 42, 1, 'cs-CZ', N'Busy', N'Bylo obsazeno'
EXEC DefineLiteralLookup 42, 2, 'cs-CZ', N'Canceled', N'Zrušený'
EXEC DefineLiteralLookup 42, 3, 'cs-CZ', N'Completed', N'Vyřízený'
EXEC DefineLiteralLookup 42, 4, 'cs-CZ', N'Failed', N'Selhalo volání'
EXEC DefineLiteralLookup 42, 5, 'cs-CZ', N'Neglected', N'Upuštěno'
EXEC DefineLiteralLookup 42, 6, 'cs-CZ', N'NoAnswer', N'Nikdo nevzal'
EXEC DefineLiteralLookup 42, 7, 'cs-CZ', N'NoResult', N'Bez výsledku'
EXEC DefineLiteralLookup 42, 8, 'cs-CZ', N'Paused', N'Pozastaven'
EXEC DefineLiteralLookup 42, 9, 'cs-CZ', N'Prepared', N'Připraven'
EXEC DefineLiteralLookup 42, 10, 'cs-CZ', N'Scheduled', N'Naplánován'
EXEC DefineLiteralLookup 42, 11, 'cs-CZ', N'TalkError', N'Omyl'
EXEC DefineLiteralLookup 42, 12, 'cs-CZ', N'ToContinue', N'Bude pokračovat'
EXEC DefineLiteralLookup 42, 13, 'cs-CZ', N'ReplaceNumber', N'Změna čísla'

EXEC DefineLiteralLookup 0, 43, 'cs-CZ', N'OutboundCall_CallPhase', N'Odchozí hovor - Fáze zpracování'
EXEC DefineLiteralLookup 43, 0, 'cs-CZ', N'AgentDialing', N'Vytáčení'
EXEC DefineLiteralLookup 43, 1, 'cs-CZ', N'AgentOfferFirst', N'První nabídka'
EXEC DefineLiteralLookup 43, 2, 'cs-CZ', N'AgentOfferMissed', N'Zmeškaná nabídka'
EXEC DefineLiteralLookup 43, 3, 'cs-CZ', N'AgentOfferNext', N'Další nabídka'
EXEC DefineLiteralLookup 43, 4, 'cs-CZ', N'AgentPreCall', N'Náhled'
EXEC DefineLiteralLookup 43, 5, 'cs-CZ', N'AgentTalk', N'Hovor'
EXEC DefineLiteralLookup 43, 6, 'cs-CZ', N'Enqueue', N'Distribuce'
EXEC DefineLiteralLookup 43, 7, 'cs-CZ', N'EnqueueNoTime', N'Pozdě'
EXEC DefineLiteralLookup 43, 8, 'cs-CZ', N'EnqueueTimedOut', N'Propásnutý'
EXEC DefineLiteralLookup 43, 9, 'cs-CZ', N'Obsolete', N'Zbytečný'
EXEC DefineLiteralLookup 43, 10, 'cs-CZ', N'HangupAgent', N'Zavěsil agent'
EXEC DefineLiteralLookup 43, 11, 'cs-CZ', N'HangupCalled', N'Zavěsil volaný'
EXEC DefineLiteralLookup 43, 12, 'cs-CZ', N'New', N'Nový'
EXEC DefineLiteralLookup 43, 13, 'cs-CZ', N'Manual', N'Manuální plánování'
EXEC DefineLiteralLookup 43, 14, 'cs-CZ', N'WaitForResult', N'Čekám na výsledek'
EXEC DefineLiteralLookup 43, 15, 'cs-CZ', N'AutoDial', N'Auto vytáčení'
EXEC DefineLiteralLookup 43, 16, 'cs-CZ', N'IvrScriptA', N'IVR A'
EXEC DefineLiteralLookup 43, 17, 'cs-CZ', N'TerminatedA', N'Ukončení A'

EXEC DefineLiteralLookup 0, 44, 'cs-CZ', N'CallEvent_EventType', N'Událost hovoru - Typ'
EXEC DefineLiteralLookup 44, 0, 'cs-CZ', N'Pilot', N'Pilot'
EXEC DefineLiteralLookup 44, 1, 'cs-CZ', N'DirectEntry', N'Přímý vstup'
EXEC DefineLiteralLookup 44, 2, 'cs-CZ', N'PreCondition', N'Vstupní pravidlo'
EXEC DefineLiteralLookup 44, 3, 'cs-CZ', N'AnnouncementA', N'Hláska A'
EXEC DefineLiteralLookup 44, 4, 'cs-CZ', N'IvrScriptA', N'IVR A'
EXEC DefineLiteralLookup 44, 5, 'cs-CZ', N'ProjectCondition', N'Projektové pravidlo'
EXEC DefineLiteralLookup 44, 6, 'cs-CZ', N'PostCondition', N'Distribuční pravidlo'
EXEC DefineLiteralLookup 44, 7, 'cs-CZ', N'AnnouncementB', N'Hláska B'
EXEC DefineLiteralLookup 44, 8, 'cs-CZ', N'IvrScriptB', N'IVR B'
EXEC DefineLiteralLookup 44, 9, 'cs-CZ', N'Enqueued', N'Distribuováno'
EXEC DefineLiteralLookup 44, 10, 'cs-CZ', N'WaitPostCondition', N'Čekací pravidlo'
EXEC DefineLiteralLookup 44, 11, 'cs-CZ', N'Waiting', N'Čekání'
EXEC DefineLiteralLookup 44, 12, 'cs-CZ', N'AnnouncementW', N'Hláska čekací'
EXEC DefineLiteralLookup 44, 13, 'cs-CZ', N'IvrScriptW', N'IVR čekací'
EXEC DefineLiteralLookup 44, 14, 'cs-CZ', N'AgentRing', N'Zvonění'
EXEC DefineLiteralLookup 44, 15, 'cs-CZ', N'AgentMissed', N'Změškáno'
EXEC DefineLiteralLookup 44, 16, 'cs-CZ', N'AgentAnswer', N'Zvednuto'
EXEC DefineLiteralLookup 44, 17, 'cs-CZ', N'CallLost', N'Ztraceno'
EXEC DefineLiteralLookup 44, 18, 'cs-CZ', N'HangupAgent', N'Zavěsil agent'
EXEC DefineLiteralLookup 44, 19, 'cs-CZ', N'HangupCaller', N'Zavěsil volající'
EXEC DefineLiteralLookup 44, 20, 'cs-CZ', N'ChangeMeta', N'Změna údajů'
EXEC DefineLiteralLookup 44, 21, 'cs-CZ', N'Terminated', N'Ukončeno'
EXEC DefineLiteralLookup 44, 22, 'cs-CZ', N'End', N'Konec'
EXEC DefineLiteralLookup 44, 23, 'cs-CZ', N'Error', N'Chyba'
EXEC DefineLiteralLookup 44, 24, 'cs-CZ', N'ManualDispatch', N'Manuální zvednutí'
EXEC DefineLiteralLookup 44, 25, 'cs-CZ', N'Chaining', N'Zřetězení'
EXEC DefineLiteralLookup 44, 26, 'cs-CZ', N'AgentPreCalled', N'Náhled'
EXEC DefineLiteralLookup 44, 27, 'cs-CZ', N'AgentIgnored', N'Ignorováno'
EXEC DefineLiteralLookup 44, 28, 'cs-CZ', N'AgentOffered', N'Nabídka'
EXEC DefineLiteralLookup 44, 29, 'cs-CZ', N'AgentBusy', N'Obsazeno'
EXEC DefineLiteralLookup 44, 30, 'cs-CZ', N'AgentAccepted', N'Akceptováno'
EXEC DefineLiteralLookup 44, 31, 'cs-CZ', N'AgentResult', N'Výsledek'
EXEC DefineLiteralLookup 44, 32, 'cs-CZ', N'Scenario', N'Scénář nabídnut'
EXEC DefineLiteralLookup 44, 33, 'cs-CZ', N'ScenarioOpen', N'Scénář zvolen'
EXEC DefineLiteralLookup 44, 34, 'cs-CZ', N'ScenarioResult', N'Scénář uložen'
EXEC DefineLiteralLookup 44, 35, 'cs-CZ', N'ScenarioRebound', N'Scénář přepojen'
EXEC DefineLiteralLookup 44, 36, 'cs-CZ', N'CalledConnect', N'Volaný zvednul'
EXEC DefineLiteralLookup 44, 37, 'cs-CZ', N'NoAnswer', N'Volaný nezvedá'
EXEC DefineLiteralLookup 44, 38, 'cs-CZ', N'HangupCalled', N'Zavěsil volaný'
EXEC DefineLiteralLookup 44, 39, 'cs-CZ', N'Scheduled', N'Naplánován'
EXEC DefineLiteralLookup 44, 40, 'cs-CZ', N'Paused', N'Pozastaven'
EXEC DefineLiteralLookup 44, 41, 'cs-CZ', N'Rescheduled', N'Přeplánován'
EXEC DefineLiteralLookup 44, 42, 'cs-CZ', N'NextTrial', N'Další pokus'
EXEC DefineLiteralLookup 44, 43, 'cs-CZ', N'Neglected', N'Upuštěno od volání'
EXEC DefineLiteralLookup 44, 44, 'cs-CZ', N'Rejected', N'Odmítnuto agentem'
EXEC DefineLiteralLookup 44, 45, 'cs-CZ', N'ExpiredTrial', N'Vyčerpány pokusy'
EXEC DefineLiteralLookup 44, 46, 'cs-CZ', N'Canceled', N'Zrušeno'
EXEC DefineLiteralLookup 44, 47, 'cs-CZ', N'QuotaReached', N'Dosažena kvóta'
EXEC DefineLiteralLookup 44, 48, 'cs-CZ', N'ImportRebound', N'Import přepojen'
EXEC DefineLiteralLookup 44, 49, 'cs-CZ', N'VoiceMail', N'Hlasová pošta'
EXEC DefineLiteralLookup 44, 50, 'cs-CZ', N'NewCall', N'Nový hovor'
EXEC DefineLiteralLookup 44, 51, 'cs-CZ', N'LostCall', N'Náhradní volání'
EXEC DefineLiteralLookup 44, 52, 'cs-CZ', N'CallBack', N'Zpětné volání'
EXEC DefineLiteralLookup 44, 53, 'cs-CZ', N'AgentChange', N'Změna agenta'
EXEC DefineLiteralLookup 44, 54, 'cs-CZ', N'IssueChange', N'Změna případu'
EXEC DefineLiteralLookup 44, 55, 'cs-CZ', N'ProjectChange', N'Změna projektu'
EXEC DefineLiteralLookup 44, 56, 'cs-CZ', N'LangChange', N'Změna jazyka'
EXEC DefineLiteralLookup 44, 57, 'cs-CZ', N'ContactChange', N'Změna kontaktu'
EXEC DefineLiteralLookup 44, 58, 'cs-CZ', N'Saved', N'Uložení hovoru'

EXEC DefineLiteralLookup 0, 45, 'cs-CZ', N'CallEvent_ReferenceData', N'Událost hovoru - Referenční data'
EXEC DefineLiteralLookup 45, 0, 'cs-CZ', N'OK', N'OK'
EXEC DefineLiteralLookup 45, 1, 'cs-CZ', N'Error', N'Chyba'
EXEC DefineLiteralLookup 45, 2, 'cs-CZ', N'Start', N'Start'
EXEC DefineLiteralLookup 45, 3, 'cs-CZ', N'Stop', N'Stop'
EXEC DefineLiteralLookup 45, 4, 'cs-CZ', N'WaitingQueue', N'Čekací fronta'
EXEC DefineLiteralLookup 45, 5, 'cs-CZ', N'Passive', N'Pasivní'
EXEC DefineLiteralLookup 45, 6, 'cs-CZ', N'Ivr', N'Z IVR'
EXEC DefineLiteralLookup 45, 7, 'cs-CZ', N'Manual', N'Ruční'
EXEC DefineLiteralLookup 45, 8, 'cs-CZ', N'IssueCall', N'Z případu'
EXEC DefineLiteralLookup 45, 9, 'cs-CZ', N'ParamCall', N'Dle zadání'
EXEC DefineLiteralLookup 45, 10, 'cs-CZ', N'Shifted', N'Převeden'
EXEC DefineLiteralLookup 45, 11, 'cs-CZ', N'Skipped', N'Přeskočen'
EXEC DefineLiteralLookup 45, 12, 'cs-CZ', N'Meantime', N'V mezičase'

EXEC DefineLiteralLookup 0, 46, 'cs-CZ', N'OutboundList_Activity', N'Odchozí kampaň - Aktivita'
EXEC DefineLiteralLookup 46, 0, 'cs-CZ', N'Prepared', N'Připravena'
EXEC DefineLiteralLookup 46, 1, 'cs-CZ', N'Scheduled', N'Spuštěna'
EXEC DefineLiteralLookup 46, 2, 'cs-CZ', N'Paused', N'Pozastavena'
EXEC DefineLiteralLookup 46, 3, 'cs-CZ', N'Completed', N'Dokončena'

EXEC DefineLiteralLookup 0, 50, 'cs-CZ', N'Message_MessageType', N'Zpráva - Typ'
EXEC DefineLiteralLookup 50, 0, 'cs-CZ', N'Email', N'Email'
EXEC DefineLiteralLookup 50, 1, 'cs-CZ', N'Fax', N'Fax'
EXEC DefineLiteralLookup 50, 2, 'cs-CZ', N'SocMsg', N'Zpráva'
EXEC DefineLiteralLookup 50, 3, 'cs-CZ', N'SocWall', N'Příspěvek'
EXEC DefineLiteralLookup 50, 4, 'cs-CZ', N'SMS', N'SMS'
EXEC DefineLiteralLookup 50, 5, 'cs-CZ', N'Task', N'Úkol'
EXEC DefineLiteralLookup 50, 6, 'cs-CZ', N'Note', N'Poznámka'
EXEC DefineLiteralLookup 50, 7, 'cs-CZ', N'Tmp', N'Šablona'
EXEC DefineLiteralLookup 50, 8, 'cs-CZ', N'TmpEmail', N'Šablona emailu'
EXEC DefineLiteralLookup 50, 9, 'cs-CZ', N'TmpFax', N'Šablona faxu'
EXEC DefineLiteralLookup 50, 10, 'cs-CZ', N'TmpSMS', N'Šablona SMS'
EXEC DefineLiteralLookup 50, 11, 'cs-CZ', N'TmpTask', N'Šablona úkolu'
EXEC DefineLiteralLookup 50, 12, 'cs-CZ', N'TmpNote', N'Šablona poznámky'

EXEC DefineLiteralLookup 0, 51, 'cs-CZ', N'Message_Direction', N'Zpráva - Směr'
EXEC DefineLiteralLookup 51, 0, 'cs-CZ', N'I', N'Příchozí'
EXEC DefineLiteralLookup 51, 1, 'cs-CZ', N'O', N'Odchozí'

EXEC DefineLiteralLookup 0, 52, 'cs-CZ', N'Message_MessagePhase', N'Zpráva - Fáze zpracování'
EXEC DefineLiteralLookup 52, 0, 'cs-CZ', N'Receiving', N'Doručuje se'
EXEC DefineLiteralLookup 52, 1, 'cs-CZ', N'Received', N'Doručeno'
EXEC DefineLiteralLookup 52, 2, 'cs-CZ', N'Read', N'Přečteno'
EXEC DefineLiteralLookup 52, 3, 'cs-CZ', N'Accepted', N'Přijmuto'
EXEC DefineLiteralLookup 52, 4, 'cs-CZ', N'Answering', N'Odpovídá se'
EXEC DefineLiteralLookup 52, 5, 'cs-CZ', N'Closed', N'Uzavřeno'
EXEC DefineLiteralLookup 52, 6, 'cs-CZ', N'Terminated', N'Ukončeno'
EXEC DefineLiteralLookup 52, 7, 'cs-CZ', N'Draft', N'Koncept'
EXEC DefineLiteralLookup 52, 8, 'cs-CZ', N'Scheduled', N'Naplánováno'
EXEC DefineLiteralLookup 52, 9, 'cs-CZ', N'Failed', N'Selhalo'
EXEC DefineLiteralLookup 52, 10, 'cs-CZ', N'Sent', N'Odesláno'
EXEC DefineLiteralLookup 52, 11, 'cs-CZ', N'Confirmed', N'Potvrzeno'
EXEC DefineLiteralLookup 52, 12, 'cs-CZ', N'Canceled', N'Zrušeno'
EXEC DefineLiteralLookup 52, 13, 'cs-CZ', N'New', N'Nový'
EXEC DefineLiteralLookup 52, 14, 'cs-CZ', N'Hold', N'Odložený'
EXEC DefineLiteralLookup 52, 15, 'cs-CZ', N'Open', N'Otevřený'
EXEC DefineLiteralLookup 52, 16, 'cs-CZ', N'Wait', N'Čekáme'

EXEC DefineLiteralLookup 0, 53, 'cs-CZ', N'Message_MessageResult', N'Zpráva - Výsledek zpracování'
EXEC DefineLiteralLookup 53, 0, 'cs-CZ', N'Active', N'Aktivní'
EXEC DefineLiteralLookup 53, 1, 'cs-CZ', N'Answered', N'Odpověď'
EXEC DefineLiteralLookup 53, 2, 'cs-CZ', N'Closed', N'Vyřízeno'

EXEC DefineLiteralLookup 0, 54, 'cs-CZ', N'Message_SpamLevel', N'Zpráva - Úroveň spamu'
EXEC DefineLiteralLookup 54, 0, 'cs-CZ', N'0', N'Není spam'
EXEC DefineLiteralLookup 54, 1, 'cs-CZ', N'1', N'Spam vyřazený'
EXEC DefineLiteralLookup 54, 2, 'cs-CZ', N'2', N'Spam blokovaný'
EXEC DefineLiteralLookup 54, 3, 'cs-CZ', N'3', N'Spam filtrovaný'

EXEC DefineLiteralLookup 0, 55, 'cs-CZ', N'Message_SignatureValidity', N'Zpráva - Platnost podpisu'
EXEC DefineLiteralLookup 55, 0, 'cs-CZ', N'0', N'Platný podpis'
EXEC DefineLiteralLookup 55, 1, 'cs-CZ', N'1', N'Neplatný certifikát'
EXEC DefineLiteralLookup 55, 2, 'cs-CZ', N'2', N'Certifikát není k dipsozici'
EXEC DefineLiteralLookup 55, 3, 'cs-CZ', N'3', N'Neplatný certifikát, Certifikát není k dipsozici'
EXEC DefineLiteralLookup 55, 4, 'cs-CZ', N'4', N'Podpis není platný'
EXEC DefineLiteralLookup 55, 5, 'cs-CZ', N'5', N'Neplatný certifikát, Podpis není platný'
EXEC DefineLiteralLookup 55, 6, 'cs-CZ', N'6', N'Certifikát není k dipsozici, Podpis není platný'
EXEC DefineLiteralLookup 55, 7, 'cs-CZ', N'7', N'Neplatný certifikát, Certifikát není k dipsozici, Podpis není platný'
EXEC DefineLiteralLookup 55, 8, 'cs-CZ', N'8', N'Chybí odesílatel'
EXEC DefineLiteralLookup 55, 9, 'cs-CZ', N'9', N'Neplatný certifikát, Chybí odesílatel'
EXEC DefineLiteralLookup 55, 10, 'cs-CZ', N'10', N'Certifikát není k dipsozici, Chybí odesílatel'
EXEC DefineLiteralLookup 55, 11, 'cs-CZ', N'11', N'Neplatný certifikát, Certifikát není k dipsozici, Chybí odesílatel'
EXEC DefineLiteralLookup 55, 12, 'cs-CZ', N'12', N'Podpis není platný, Chybí odesílatel'
EXEC DefineLiteralLookup 55, 13, 'cs-CZ', N'13', N'Neplatný certifikát, Podpis není platný, Chybí odesílatel'
EXEC DefineLiteralLookup 55, 14, 'cs-CZ', N'14', N'Certifikát není k dipsozici, Podpis není platný, Chybí odesílatel'
EXEC DefineLiteralLookup 55, 15, 'cs-CZ', N'15', N'Neplatný certifikát, Certifikát není k dipsozici, Podpis není platný, Chybí odesílatel'
EXEC DefineLiteralLookup 55, 16, 'cs-CZ', N'16', N'Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 17, 'cs-CZ', N'17', N'Neplatný certifikát, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 18, 'cs-CZ', N'18', N'Certifikát není k dipsozici, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 19, 'cs-CZ', N'19', N'Neplatný certifikát, Certifikát není k dipsozici, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 20, 'cs-CZ', N'20', N'Podpis není platný, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 21, 'cs-CZ', N'21', N'Neplatný certifikát, Podpis není platný, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 22, 'cs-CZ', N'22', N'Certifikát není k dipsozici, Podpis není platný, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 23, 'cs-CZ', N'23', N'Neplatný certifikát, Certifikát není k dipsozici, Podpis není platný, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 24, 'cs-CZ', N'24', N'Chybí odesílatel, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 25, 'cs-CZ', N'25', N'Neplatný certifikát, Chybí odesílatel, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 26, 'cs-CZ', N'26', N'Certifikát není k dipsozici, Chybí odesílatel, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 27, 'cs-CZ', N'27', N'Neplatný certifikát, Certifikát není k dipsozici, Chybí odesílatel, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 28, 'cs-CZ', N'28', N'Podpis není platný, Chybí odesílatel, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 29, 'cs-CZ', N'29', N'Neplatný certifikát, Podpis není platný, Chybí odesílatel, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 30, 'cs-CZ', N'30', N'Certifikát není k dipsozici, Podpis není platný, Chybí odesílatel, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, 31, 'cs-CZ', N'31', N'Neplatný certifikát, Certifikát není k dipsozici, Podpis není platný, Chybí odesílatel, Chybí podpis odesílatele'
EXEC DefineLiteralLookup 55, -1, 'cs-CZ', N'-1', N'Nepodepsáno'

EXEC DefineLiteralLookup 0, 56, 'cs-CZ', N'MessageEvent_EventType', N'Událost zprávy - Typ'
EXEC DefineLiteralLookup 56, 0, 'cs-CZ', N'Received', N'Doručena'
EXEC DefineLiteralLookup 56, 1, 'cs-CZ', N'ReceivedMultiple', N'Doručena více'
EXEC DefineLiteralLookup 56, 2, 'cs-CZ', N'WithReplyTo', N'Obsahuje Odpovědět na'
EXEC DefineLiteralLookup 56, 3, 'cs-CZ', N'SignatureValid', N'Platný digitální podpis'
EXEC DefineLiteralLookup 56, 4, 'cs-CZ', N'SignatureInvalid', N'Neplatný digitální podpis'
EXEC DefineLiteralLookup 56, 5, 'cs-CZ', N'PreCondition', N'Vstupní pravidlo'
EXEC DefineLiteralLookup 56, 6, 'cs-CZ', N'ImrScriptA', N'IMR A'
EXEC DefineLiteralLookup 56, 7, 'cs-CZ', N'ProjectCondition', N'Projektové pravidlo'
EXEC DefineLiteralLookup 56, 8, 'cs-CZ', N'PostCondition', N'Distribuční pravidlo'
EXEC DefineLiteralLookup 56, 9, 'cs-CZ', N'ImrScriptB', N'IMR B'
EXEC DefineLiteralLookup 56, 10, 'cs-CZ', N'Enqueued', N'Zařazena'
EXEC DefineLiteralLookup 56, 11, 'cs-CZ', N'Reading', N'Přečtena'
EXEC DefineLiteralLookup 56, 12, 'cs-CZ', N'Accepting', N'Přijmuta'
EXEC DefineLiteralLookup 56, 13, 'cs-CZ', N'Answering', N'Odpovídána'
EXEC DefineLiteralLookup 56, 14, 'cs-CZ', N'AnswerSending', N'Odpověď odeslána'
EXEC DefineLiteralLookup 56, 15, 'cs-CZ', N'AnswerCancelling', N'Odpověď zrušena'
EXEC DefineLiteralLookup 56, 16, 'cs-CZ', N'Closing', N'Uzavřeno'
EXEC DefineLiteralLookup 56, 17, 'cs-CZ', N'Terminating', N'Ukončeno'
EXEC DefineLiteralLookup 56, 18, 'cs-CZ', N'Returning', N'Vrácena'
EXEC DefineLiteralLookup 56, 19, 'cs-CZ', N'Reactivating', N'Reaktivována'
EXEC DefineLiteralLookup 56, 20, 'cs-CZ', N'AutoReplying', N'Automatická odpověď'
EXEC DefineLiteralLookup 56, 21, 'cs-CZ', N'AutoSending', N'Automatická zpráva'
EXEC DefineLiteralLookup 56, 22, 'cs-CZ', N'Replying', N'Odpověď'
EXEC DefineLiteralLookup 56, 23, 'cs-CZ', N'Forwarding', N'Předání'
EXEC DefineLiteralLookup 56, 24, 'cs-CZ', N'Drafting', N'Koncept'
EXEC DefineLiteralLookup 56, 25, 'cs-CZ', N'Schedule', N'Naplánována'
EXEC DefineLiteralLookup 56, 26, 'cs-CZ', N'Sent', N'Odeslána'
EXEC DefineLiteralLookup 56, 27, 'cs-CZ', N'Confirmed', N'Potvrzena'
EXEC DefineLiteralLookup 56, 28, 'cs-CZ', N'Cancelling', N'Zrušena'
EXEC DefineLiteralLookup 56, 29, 'cs-CZ', N'ConvertedToEml', N'Konverze EML'
EXEC DefineLiteralLookup 56, 30, 'cs-CZ', N'Ndr', N'Nedoručenka'
EXEC DefineLiteralLookup 56, 31, 'cs-CZ', N'Failure', N'Selhání'
EXEC DefineLiteralLookup 56, 32, 'cs-CZ', N'New', N'Nový'
EXEC DefineLiteralLookup 56, 33, 'cs-CZ', N'Opening', N'Otevřený'
EXEC DefineLiteralLookup 56, 34, 'cs-CZ', N'Holding', N'Odložěný'
EXEC DefineLiteralLookup 56, 35, 'cs-CZ', N'Waiting', N'Čekající'
EXEC DefineLiteralLookup 56, 36, 'cs-CZ', N'Assigned', N'Přiřazeno'
EXEC DefineLiteralLookup 56, 37, 'cs-CZ', N'AgentChange', N'Změna agenta'
EXEC DefineLiteralLookup 56, 38, 'cs-CZ', N'IssueChange', N'Změna případu'
EXEC DefineLiteralLookup 56, 39, 'cs-CZ', N'ProjectChange', N'Změna projektu'
EXEC DefineLiteralLookup 56, 40, 'cs-CZ', N'SkillChange', N'Změna dovednosti'
EXEC DefineLiteralLookup 56, 41, 'cs-CZ', N'LangChange', N'Změna jazyka'
EXEC DefineLiteralLookup 56, 42, 'cs-CZ', N'ProfChange', N'Změna znalosti'
EXEC DefineLiteralLookup 56, 43, 'cs-CZ', N'PriorityChange', N'Změna priority'
EXEC DefineLiteralLookup 56, 44, 'cs-CZ', N'ContactChange', N'Změna kontaktu'

EXEC DefineLiteralLookup 0, 57, 'cs-CZ', N'Campaign_Activity', N'Hromadná kampaň - Aktivita'
EXEC DefineLiteralLookup 57, 0, 'cs-CZ', N'Prepared', N'Připraveno'
EXEC DefineLiteralLookup 57, 1, 'cs-CZ', N'Scheduled', N'Spuštěno'
EXEC DefineLiteralLookup 57, 2, 'cs-CZ', N'Paused', N'Pozastaveno'
EXEC DefineLiteralLookup 57, 3, 'cs-CZ', N'Completed', N'Ukončeno'

EXEC DefineLiteralLookup 0, 60, 'cs-CZ', N'Issue_Activity', N'Případ - Aktivita'
EXEC DefineLiteralLookup 60, 0, 'cs-CZ', N'New', N'Nový'
EXEC DefineLiteralLookup 60, 1, 'cs-CZ', N'Open', N'Otevřený'
EXEC DefineLiteralLookup 60, 2, 'cs-CZ', N'Hold', N'Odložený'
EXEC DefineLiteralLookup 60, 3, 'cs-CZ', N'Wait', N'Čeká'
EXEC DefineLiteralLookup 60, 4, 'cs-CZ', N'Closed', N'Uzavřený'

EXEC DefineLiteralLookup 0, 61, 'cs-CZ', N'IssueEvent_EventType', N'Událost případu - Typ'
EXEC DefineLiteralLookup 61, 0, 'cs-CZ', N'NewIssue', N'Nový'
EXEC DefineLiteralLookup 61, 1, 'cs-CZ', N'OpenIssue', N'Otevřený'
EXEC DefineLiteralLookup 61, 2, 'cs-CZ', N'HoldIssue', N'Odložený'
EXEC DefineLiteralLookup 61, 3, 'cs-CZ', N'WaitIssue', N'Čeká'
EXEC DefineLiteralLookup 61, 4, 'cs-CZ', N'ClosedIssue', N'Uzavřený'
EXEC DefineLiteralLookup 61, 5, 'cs-CZ', N'AgentChange', N'Změna agenta'
EXEC DefineLiteralLookup 61, 6, 'cs-CZ', N'ProjectChange', N'Změna projektu'
EXEC DefineLiteralLookup 61, 7, 'cs-CZ', N'LangChange', N'Změna jazka'
EXEC DefineLiteralLookup 61, 8, 'cs-CZ', N'ContactChange', N'Změna kontaktu'
EXEC DefineLiteralLookup 61, 9, 'cs-CZ', N'TopicChange', N'Změna tématu'
EXEC DefineLiteralLookup 61, 10, 'cs-CZ', N'SubTopicChange', N'Změna podtématu'
EXEC DefineLiteralLookup 61, 11, 'cs-CZ', N'DataSaved', N'Změna dat'
EXEC DefineLiteralLookup 61, 12, 'cs-CZ', N'ScenarioResult', N'Změna formuláře'

EXEC DefineLiteralLookup 0, 65, 'cs-CZ', N'ScenarioResult_Activity', N'Formulář - Aktivita'
EXEC DefineLiteralLookup 65, 0, 'cs-CZ', N'Active', N'Aktivní'
EXEC DefineLiteralLookup 65, 1, 'cs-CZ', N'Canceled', N'Zrušený'
EXEC DefineLiteralLookup 65, 2, 'cs-CZ', N'Completed', N'Dokončený'
EXEC DefineLiteralLookup 65, 3, 'cs-CZ', N'Neglected', N'Upuštěno'
EXEC DefineLiteralLookup 65, 4, 'cs-CZ', N'PreFilled', N'Předvyplněný'

EXEC DefineLiteralLookup 0, 70, 'cs-CZ', N'Paging_Activity', N'Svolávání - Aktivita'
EXEC DefineLiteralLookup 70, 0, 'cs-CZ', N'Draft', N'Koncept'
EXEC DefineLiteralLookup 70, 1, 'cs-CZ', N'Ready', N'Připraveno ke spuštění'
EXEC DefineLiteralLookup 70, 2, 'cs-CZ', N'Paused', N'Zastaveno'
EXEC DefineLiteralLookup 70, 3, 'cs-CZ', N'Active', N'Probíhá'
EXEC DefineLiteralLookup 70, 4, 'cs-CZ', N'Closed', N'Ukončeno'

EXEC DefineLiteralLookup 0, 71, 'cs-CZ', N'PagingRule_Channel', N'Pravidlo svolávání - Kanál'
EXEC DefineLiteralLookup 71, 0, 'cs-CZ', N'Voice', N'Hlas'
EXEC DefineLiteralLookup 71, 1, 'cs-CZ', N'Sms', N'Sms'
EXEC DefineLiteralLookup 71, 2, 'cs-CZ', N'Email', N'Email'

EXEC DefineLiteralLookup 0, 72, 'cs-CZ', N'PagingMember_Status', N'Člen svolávání - Stav'
EXEC DefineLiteralLookup 72, 0, 'cs-CZ', N'NotActive', N'Neaktivní'
EXEC DefineLiteralLookup 72, 1, 'cs-CZ', N'Pending', N'Čeká na odezvu'
EXEC DefineLiteralLookup 72, 2, 'cs-CZ', N'Accepted', N'Přijat'
EXEC DefineLiteralLookup 72, 3, 'cs-CZ', N'Rejected', N'Odmítnut'
EXEC DefineLiteralLookup 72, 4, 'cs-CZ', N'TimedOut', N'Vyčasován'
EXEC DefineLiteralLookup 72, 5, 'cs-CZ', N'Canceled', N'Zrušen'

EXEC DefineLiteralLookup 0, 75, 'cs-CZ', N'WorktimeType_SystemName', N'Pracovní čas - Systémový název'
EXEC DefineLiteralLookup 75, 0, 'cs-CZ', N'Work', N'Pracovní čas'
EXEC DefineLiteralLookup 75, 1, 'cs-CZ', N'NotWork', N'Nepracovní čas'
EXEC DefineLiteralLookup 75, 2, 'cs-CZ', N'WorkLoad', N'Pracovní vytížení'
EXEC DefineLiteralLookup 75, 3, 'cs-CZ', N'OpeningHours', N'Otevírací hodiny'

EXEC DefineLiteralLookup 0, 80, 'cs-CZ', N'Bool', N'Logická hodnota'
EXEC DefineLiteralLookup 80, 0, 'cs-CZ', N'true', N'Ano'
EXEC DefineLiteralLookup 80, 1, 'cs-CZ', N'false', N'Ne'

EXEC DefineLiteralLookup 0, 90, 'cs-CZ', N'BulkMessage_Activity', N'Hromadná rozesílka - Aktivita'
EXEC DefineLiteralLookup 90, 0, 'cs-CZ', N'Ready', N'Připravena'
EXEC DefineLiteralLookup 90, 1, 'cs-CZ', N'Sent', N'Odeslána'
EXEC DefineLiteralLookup 90, -1, 'cs-CZ', N'Invalid address', N'Neplatná adresa'
EXEC DefineLiteralLookup 90, -999, 'cs-CZ', N'General Error', N'Všeobecná chyba při odesílání'

EXEC DefineLiteralLookup 0, 100, 'cs-CZ', N'GeneralLocalisation', N'Lokalizace všeobecných textů'
EXEC DefineLiteralLookup 100, 0, 'cs-CZ', N'Today', N'dnes'
EXEC DefineLiteralLookup 100, 1, 'cs-CZ', N'Yesterday', N'včera'
EXEC DefineLiteralLookup 100, 2, 'cs-CZ', N'Active', N'Aktivní'
EXEC DefineLiteralLookup 100, 3, 'cs-CZ', N'Inactive', N'Neaktivní'

EXEC DefineLiteralLookup 0, 101, 'cs-CZ', N'ReactClientLocalisation', N'Lokalizace pro ReactClient'

EXEC DefineLiteralLookup 101, 100, 'cs-CZ', N'Msg_Accept', N'Přijmout'
EXEC DefineLiteralLookup 101, 101, 'cs-CZ', N'Msg_Finish', N'Vyřídit'
EXEC DefineLiteralLookup 101, 102, 'cs-CZ', N'Msg_Spam', N'Označit jako spam'
EXEC DefineLiteralLookup 101, 103, 'cs-CZ', N'Msg_UnSpam', N'Není spam'
EXEC DefineLiteralLookup 101, 104, 'cs-CZ', N'Msg_Block', N'Blokovat odesílatele a označit jako spam'
EXEC DefineLiteralLookup 101, 107, 'cs-CZ', N'Msg_Answer', N'Odpovědět'
EXEC DefineLiteralLookup 101, 108, 'cs-CZ', N'Msg_AnswerAll', N'Odpovědět všem'
EXEC DefineLiteralLookup 101, 109, 'cs-CZ', N'Msg_Forward', N'Předat dál'
EXEC DefineLiteralLookup 101, 110, 'cs-CZ', N'Msg_Return_In', N'Vrátit do fronty'
EXEC DefineLiteralLookup 101, 111, 'cs-CZ', N'Msg_Return_Out', N'Vrátit na jiného'
EXEC DefineLiteralLookup 101, 112, 'cs-CZ', N'Msg_Send', N'Odeslat'
EXEC DefineLiteralLookup 101, 113, 'cs-CZ', N'Msg_Cancel', N'Zrušit'
EXEC DefineLiteralLookup 101, 114, 'cs-CZ', N'Msg_Back', N'Zrušit a vrátit se k původní zprávě'
EXEC DefineLiteralLookup 101, 115, 'cs-CZ', N'Msg_AddAttachment', N'Vložit přílohu'
EXEC DefineLiteralLookup 101, 116, 'cs-CZ', N'Msg_ShowAnswer', N'Jdi na odpověď'
EXEC DefineLiteralLookup 101, 117, 'cs-CZ', N'Msg_ShowOrigin', N'Jdi na původní'
EXEC DefineLiteralLookup 101, 118, 'cs-CZ', N'Msg_Signature_OK', N'Zpráva je digitálně podepsaná a digitlní podpis je platný'
EXEC DefineLiteralLookup 101, 119, 'cs-CZ', N'Msg_Signature_Err', N'Neplatný digitální podpis, i když je zpráva digitálně podepsaná'
EXEC DefineLiteralLookup 101, 120, 'cs-CZ', N'Msg_Phase_Draft', N'Zprávu můžete editovat a měnit údaje'
EXEC DefineLiteralLookup 101, 121, 'cs-CZ', N'Msg_Phase_Answering', N'Na zprávu se již píše odpověď, tuto zprávu nelze editovat'
EXEC DefineLiteralLookup 101, 122, 'cs-CZ', N'Msg_Phase_Closed', N'Zprávu nelze editovat, už je vyřízena'
EXEC DefineLiteralLookup 101, 123, 'cs-CZ', N'Msg_Phase_Scheduled', N'Zprávu nelze editovat, čeká na odeslání, ale můžete ji např. zrušit'
EXEC DefineLiteralLookup 101, 124, 'cs-CZ', N'Msg_Phase_Sent', N'Zprávu nelze editovat, už je odeslána'
EXEC DefineLiteralLookup 101, 125, 'cs-CZ', N'Msg_Phase_Active', N'Text zprávy nelze editovat, můžete editovat ostatní údaje nebo např. odpovědět'
EXEC DefineLiteralLookup 101, 126, 'cs-CZ', N'Msg_FromLabel', N'Od'
EXEC DefineLiteralLookup 101, 127, 'cs-CZ', N'Msg_ToLabel', N'Komu'
EXEC DefineLiteralLookup 101, 128, 'cs-CZ', N'Msg_CcLabel', N'Kopie'
EXEC DefineLiteralLookup 101, 129, 'cs-CZ', N'Msg_BccLabel', N'Skrytá'
EXEC DefineLiteralLookup 101, 130, 'cs-CZ', N'Msg_EmailAddressLabel', N'Emailová adresa...'
EXEC DefineLiteralLookup 101, 131, 'cs-CZ', N'Msg_SubjectLabel', N'Předmět...'
EXEC DefineLiteralLookup 101, 133, 'cs-CZ', N'Msg_Direction_In', N'Došlá zpráva'
EXEC DefineLiteralLookup 101, 134, 'cs-CZ', N'Msg_Direction_Out', N'Odeslaná zpráva'
EXEC DefineLiteralLookup 101, 135, 'cs-CZ', N'Msg_Direction_Draft', N'Koncept odesílané zprávy'
EXEC DefineLiteralLookup 101, 136, 'cs-CZ', N'Msg_MessageType', N'Typ zprávy'
EXEC DefineLiteralLookup 101, 137, 'cs-CZ', N'Msg_SelectTemplateTitle', N'Vyberte šablonu, která se má vložit'
EXEC DefineLiteralLookup 101, 145, 'cs-CZ', N'Msg_CampaignLabel', N'Kampaň'
EXEC DefineLiteralLookup 101, 149, 'cs-CZ', N'Msg_PersoTypeaheadSection', N'Při hledání adresy prohledávat'
EXEC DefineLiteralLookup 101, 157, 'cs-CZ', N'Msg_DraftTimeLabel', N'Čas zahájení psaní'
EXEC DefineLiteralLookup 101, 158, 'cs-CZ', N'Msg_ScheduledTimeLabel', N'Neodesílat před časem'
EXEC DefineLiteralLookup 101, 159, 'cs-CZ', N'Msg_SentTimeLabel', N'Čas odeslání'
EXEC DefineLiteralLookup 101, 160, 'cs-CZ', N'Msg_ReceiveTimeLabel ', N'Čas doručení'
EXEC DefineLiteralLookup 101, 161, 'cs-CZ', N'Msg_AcceptedTimeLabel', N'Čas přijmutí k vyřízení'
EXEC DefineLiteralLookup 101, 162, 'cs-CZ', N'Msg_AnsweringTimeLabel', N'Čas zahájení psaní odpovědi'
EXEC DefineLiteralLookup 101, 163, 'cs-CZ', N'Msg_EndTimeLabel', N'Čas ukončení zpracování'
EXEC DefineLiteralLookup 101, 164, 'cs-CZ', N'Msg_Title', N'Zpráva'

EXEC DefineLiteralLookup 101, 200, 'cs-CZ', N'Iss_AgentLabel', N'Agent'
EXEC DefineLiteralLookup 101, 201, 'cs-CZ', N'Iss_ProjectLabel', N'Projekt'
EXEC DefineLiteralLookup 101, 202, 'cs-CZ', N'Iss_LanguageLabel', N'Jazyk'
EXEC DefineLiteralLookup 101, 203, 'cs-CZ', N'Iss_TopicLabel', N'Téma'
EXEC DefineLiteralLookup 101, 204, 'cs-CZ', N'Iss_SubTopicLabel', N'Podtéma'
EXEC DefineLiteralLookup 101, 205, 'cs-CZ', N'Iss_PhaseLabel', N'Fáze'
EXEC DefineLiteralLookup 101, 206, 'cs-CZ', N'Iss_NewTime', N'Čas vzniku případu'
EXEC DefineLiteralLookup 101, 207, 'cs-CZ', N'Iss_CreateNew', N'Vytvořit nový případ'
EXEC DefineLiteralLookup 101, 208, 'cs-CZ', N'Iss_Change', N'Vybrat jiný existující případ'
EXEC DefineLiteralLookup 101, 209, 'cs-CZ', N'Iss_Remove', N'Odebrat přiřazený případ'
EXEC DefineLiteralLookup 101, 210, 'cs-CZ', N'Iss_Close', N'Uložit a uzavřít případ'
EXEC DefineLiteralLookup 101, 211, 'cs-CZ', N'Iss_CannotClose', N'Případ nelze nyní uzavřít'
EXEC DefineLiteralLookup 101, 212, 'cs-CZ', N'Iss_NoIssue', N'Žádný případ'
EXEC DefineLiteralLookup 101, 213, 'cs-CZ', N'Iss_CannotCreateNew', N'Nelze vytvořit nový případ'
EXEC DefineLiteralLookup 101, 214, 'cs-CZ', N'Iss_SelectIssueTitle', N'Vyberte případ, ke kterému se má přiřadit'

EXEC DefineLiteralLookup 101, 300, 'cs-CZ', N'Ctc_ModelLabel', N'Druh'
EXEC DefineLiteralLookup 101, 301, 'cs-CZ', N'Ctc_NoContact', N'Žádný záznam'
EXEC DefineLiteralLookup 101, 302, 'cs-CZ', N'Ctc_ExternalKeyLabel', N'Externí klíč'
EXEC DefineLiteralLookup 101, 303, 'cs-CZ', N'Ctc_ChangeTime', N'Změněno'
EXEC DefineLiteralLookup 101, 304, 'cs-CZ', N'Ctc_ParentContactLabel', N'Nadřazený'
EXEC DefineLiteralLookup 101, 305, 'cs-CZ', N'Ctc_CreateNew', N'Vytvořit nový záznam'
EXEC DefineLiteralLookup 101, 306, 'cs-CZ', N'Ctc_CannotCreateNew', N'Nemůžete vytvořit nový záznam'
EXEC DefineLiteralLookup 101, 307, 'cs-CZ', N'Ctc_Change', N'Vybrat jiný existující záznam'
EXEC DefineLiteralLookup 101, 308, 'cs-CZ', N'Ctc_Remove', N'Odebrat přiřazený záznam'
EXEC DefineLiteralLookup 101, 309, 'cs-CZ', N'Ctc_SelectContactTitle', N'Výberte záznam, ke kterému se má přiřadit'

EXEC DefineLiteralLookup 101, 405, 'cs-CZ', N'IC_RedirectorLabel', N'Vstupní provolba'
EXEC DefineLiteralLookup 101, 406, 'cs-CZ', N'IC_PilotLabel', N'Vstupní pilot'
EXEC DefineLiteralLookup 101, 407, 'cs-CZ', N'IC_CallerLabel', N'Číslo volajícího'
EXEC DefineLiteralLookup 101, 408, 'cs-CZ', N'IC_WorkplaceLabel', N'Pracoviště'
EXEC DefineLiteralLookup 101, 409, 'cs-CZ', N'IC_ShowChainingNext', N'Příchozí hovor, který navazuje na tento'
EXEC DefineLiteralLookup 101, 410, 'cs-CZ', N'IC_ShowChainingPrev', N'Příchozí hovor, na který navazuje tento'
EXEC DefineLiteralLookup 101, 411, 'cs-CZ', N'IC_ShowRelatedOutbound', N'Související odchozí hovor, zpětné volání'
EXEC DefineLiteralLookup 101, 413, 'cs-CZ', N'IC_Result_Active', N'Probíhající hovor'
EXEC DefineLiteralLookup 101, 414, 'cs-CZ', N'IC_Result_Lost', N'Ztracený hovor'
EXEC DefineLiteralLookup 101, 415, 'cs-CZ', N'IC_Result_Served', N'Obsloužený hovor'
EXEC DefineLiteralLookup 101, 419, 'cs-CZ', N'IC_PilotTimeLabel', N'Čas příchodu hovoru'
EXEC DefineLiteralLookup 101, 420, 'cs-CZ', N'IC_EnqueueingTimeLabel', N'Čas předání k distribuci'
EXEC DefineLiteralLookup 101, 421, 'cs-CZ', N'IC_DistributionTimeLabel', N'Čas distribuce na agenta'
EXEC DefineLiteralLookup 101, 422, 'cs-CZ', N'IC_AnswerTimeLabel', N'Čas vyzvednutí agentem'
EXEC DefineLiteralLookup 101, 423, 'cs-CZ', N'IC_EndTimeLabel', N'Čas ukončení hovoru'
EXEC DefineLiteralLookup 101, 424, 'cs-CZ', N'IC_PostCallEndTimeLabel', N'Čas dokončení zpracování'
EXEC DefineLiteralLookup 101, 425, 'cs-CZ', N'IC_Type_PilotIn', N'Projektový hovor'
EXEC DefineLiteralLookup 101, 426, 'cs-CZ', N'IC_Type_Direct', N'Přímý hovor'
EXEC DefineLiteralLookup 101, 427, 'cs-CZ', N'IC_CallBack', N'Zavolat zpět'
EXEC DefineLiteralLookup 101, 428, 'cs-CZ', N'IC_Title', N'Příchozí hovor'

EXEC DefineLiteralLookup 101, 450, 'cs-CZ', N'OC_OutboundListLabel', N'Odchozí kampaň'
EXEC DefineLiteralLookup 101, 451, 'cs-CZ', N'OC_DisplayNameLabel', N'Název hovoru'
EXEC DefineLiteralLookup 101, 452, 'cs-CZ', N'OC_CalledLabel', N'Číslo volaného'
EXEC DefineLiteralLookup 101, 453, 'cs-CZ', N'OC_WorkplaceLabel', N'Pracoviště'
EXEC DefineLiteralLookup 101, 454, 'cs-CZ', N'OC_ShowChainingNext', N'Odchozí hovor, který navazuje na tento'
EXEC DefineLiteralLookup 101, 455, 'cs-CZ', N'OC_ShowChainingPrev', N'Odchozí hovor, na který navazuje tento'
EXEC DefineLiteralLookup 101, 456, 'cs-CZ', N'OC_ShowRelatedInbound', N'Související příchozí hovor'
EXEC DefineLiteralLookup 101, 457, 'cs-CZ', N'OC_Result_Active', N'Probíhající hovor'
EXEC DefineLiteralLookup 101, 458, 'cs-CZ', N'OC_Result_Draft', N'Hovor před zpracováním'
EXEC DefineLiteralLookup 101, 459, 'cs-CZ', N'OC_Result_Done', N'Zpracovaný hovor'
EXEC DefineLiteralLookup 101, 460, 'cs-CZ', N'OC_ResultDetail', N'Podrobný výsledek'
EXEC DefineLiteralLookup 101, 461, 'cs-CZ', N'OC_DraftTimeLabel', N'Čas založení hovoru'
EXEC DefineLiteralLookup 101, 462, 'cs-CZ', N'OC_EnqueueingTimeLabel', N'Čas předání k distribuci'
EXEC DefineLiteralLookup 101, 463, 'cs-CZ', N'OC_DialTimeLabel', N'Čas vytočení hovoru agentem'
EXEC DefineLiteralLookup 101, 464, 'cs-CZ', N'OC_AnswerTimeLabel', N'Čas vyzvednutí volaným'
EXEC DefineLiteralLookup 101, 465, 'cs-CZ', N'OC_EndTimeLabel', N'Čas ukončení hovoru'
EXEC DefineLiteralLookup 101, 466, 'cs-CZ', N'OC_PostCallEndTimeLabel', N'Čas dokončení zpracování'
EXEC DefineLiteralLookup 101, 467, 'cs-CZ', N'OC_Type_DialOut', N'Projektový hovor'
EXEC DefineLiteralLookup 101, 468, 'cs-CZ', N'OC_Type_Private', N'Privátní hovor'
EXEC DefineLiteralLookup 101, 469, 'cs-CZ', N'OC_ReCall', N'Zavolat znovu'
EXEC DefineLiteralLookup 101, 470, 'cs-CZ', N'OC_OutboundListImportLabel', N'Import kampaně'
EXEC DefineLiteralLookup 101, 471, 'cs-CZ', N'OC_Title', N'Odchozí hovor'
EXEC DefineLiteralLookup 101, 472, 'cs-CZ', N'OC_Cancel', N'Zrušit hovor'
EXEC DefineLiteralLookup 101, 473, 'cs-CZ', N'OC_Neglect', N'Upustit od hovoru'
EXEC DefineLiteralLookup 101, 474, 'cs-CZ', N'OC_Pause', N'Pozastavit, tak aby se dal editovat'
EXEC DefineLiteralLookup 101, 475, 'cs-CZ', N'OC_Schedule', N'Naplánovat k zavolání'
EXEC DefineLiteralLookup 101, 476, 'cs-CZ', N'OC_ScheduleOnMe', N'Naplánovat k zavolání na mne'
EXEC DefineLiteralLookup 101, 477, 'cs-CZ', N'OC_Result_DraftEditable', N'Návrh hovoru, lze editovat'
EXEC DefineLiteralLookup 101, 478, 'cs-CZ', N'OC_CallNumberLabel', N'Telefonní číslo ...'
EXEC DefineLiteralLookup 101, 479, 'cs-CZ', N'OC_PersoTypeaheadSection', N'Při hledání telefonního čísla prohledávat'

EXEC DefineLiteralLookup 101, 900, 'cs-CZ', N'Cmn_DdnNotSelected', N'(žádná hodnota)'
EXEC DefineLiteralLookup 101, 901, 'cs-CZ', N'Cmn_ConfirmCloseUnsaved', N'Provedli jste změny, které dosud nebyly uloženy.'
EXEC DefineLiteralLookup 101, 902, 'cs-CZ', N'Cmn_DateFormat', N'd.m.Y'
EXEC DefineLiteralLookup 101, 903, 'cs-CZ', N'Cmn_DateRegex', N'^\s*(?<D>0?[1-9]|[12][0-9]|3[01])\.(?<M>0?[1-9]|1[012])\.(?<Y>[12]\d\d\d|\d\d)?\s*$'
EXEC DefineLiteralLookup 101, 904, 'cs-CZ', N'Cmn_DateHelp', N'Zadejte datum ve tvaru DD.MM.RR nebo DD.MM.RRRR nebo DD.MM. (pro aktuální rok) - např. 12.7.14. Datum smí být od 1.1.1753 do 31.12.2999.'
EXEC DefineLiteralLookup 101, 905, 'cs-CZ', N'Cmn_TimeFormat', N'h:N:S'
EXEC DefineLiteralLookup 101, 906, 'cs-CZ', N'Cmn_TimeRegex', N'^\s*(?<H>0?[0-9]|1[0-9]|2[0-3])\:(?<N>[0-5][0-9])\:?(?<S>[0-5][0-9])?\s*$'
EXEC DefineLiteralLookup 101, 907, 'cs-CZ', N'Cmn_TimeHelp', N'Zadejte čas ve tvaru HH:MM:SS nebo HH:MM - např. 9:05'
EXEC DefineLiteralLookup 101, 908, 'cs-CZ', N'Cmn_DateTimeFormat', N'd.m.Y h:N'
EXEC DefineLiteralLookup 101, 909, 'cs-CZ', N'Cmn_DateTimeRegex', N'^\s*(?<D>0?[1-9]|[12][0-9]|3[01])\.(?<M>0?[1-9]|1[012])\.(?<Y>[12]\d\d\d|\d\d)?\s*(?<H>0?[0-9]|1[0-9]|2[0-3])\:(?<N>[0-5][0-9])\:?(?<S>[0-5][0-9])?\s*$'
EXEC DefineLiteralLookup 101, 910, 'cs-CZ', N'Cmn_DateTimeHelp', N'Zadejte datum a čas (oddělené mezerou), datum ve tvaru DD.MM.RR nebo DD.MM.RRRR nebo DD.MM. (pro aktuální rok) a čas ve tvaru HH:MM:SS nebo HH:MM - např. 3.8.2015 15:30. Datum smí být od 1.1.1753 do 31.12.2999.'
EXEC DefineLiteralLookup 101, 911, 'cs-CZ', N'Cmn_SelectCultureTitle', N'Zvolte jazyk vašeho prostředí'
EXEC DefineLiteralLookup 101, 912, 'cs-CZ', N'Cmn_SelectCultureHelp', N'Změna jazyka prostředí se projeví až při příštím otevření oken aplikace, nebo ji můžete vyvolat stiskem F5 v každém okně. Nezapomeňte předtím uložit případný změněný obsah.'
EXEC DefineLiteralLookup 101, 913, 'cs-CZ', N'Cmn_AgentLabel', N'Agent'
EXEC DefineLiteralLookup 101, 914, 'cs-CZ', N'Cmn_ProjectLabel', N'Projekt'
EXEC DefineLiteralLookup 101, 915, 'cs-CZ', N'Cmn_LanguageLabel', N'Jazyk'
EXEC DefineLiteralLookup 101, 916, 'cs-CZ', N'Cmn_InfoTab', N'Info'
EXEC DefineLiteralLookup 101, 917, 'cs-CZ', N'Cmn_HistoryTab', N'Historie'
EXEC DefineLiteralLookup 101, 918, 'cs-CZ', N'Cmn_IssueTab', N'Případ'
EXEC DefineLiteralLookup 101, 919, 'cs-CZ', N'Cmn_ContactTab', N'Kontakt'
EXEC DefineLiteralLookup 101, 920, 'cs-CZ', N'Cmn_Save', N'Uložit změny'
EXEC DefineLiteralLookup 101, 921, 'cs-CZ', N'Cmn_SaveAndClose', N'Uložit změny a zavřít okno'
EXEC DefineLiteralLookup 101, 922, 'cs-CZ', N'Cmn_PersoTitle', N'Nastavení'
EXEC DefineLiteralLookup 101, 923, 'cs-CZ', N'Cmn_PersoLoading', N'Načítám nastavení ...'
EXEC DefineLiteralLookup 101, 924, 'cs-CZ', N'Cmn_PersoSave', N'Uložit'
EXEC DefineLiteralLookup 101, 925, 'cs-CZ', N'Cmn_PersoCancel', N'Storno'
EXEC DefineLiteralLookup 101, 926, 'cs-CZ', N'Cmn_Error', N'Chyba !'
EXEC DefineLiteralLookup 101, 927, 'cs-CZ', N'Cmn_PersoMaxNumberOfSuggestions', N'Počet nabízených variant'
EXEC DefineLiteralLookup 101, 928, 'cs-CZ', N'Cmn_PersoSearchStartOnly', N'Pouze začátky polí'
EXEC DefineLiteralLookup 101, 929, 'cs-CZ', N'Cmn_PersoSearchLastName', N'Příjmení'
EXEC DefineLiteralLookup 101, 930, 'cs-CZ', N'Cmn_PersoSearchFirstName', N'Jméno'
EXEC DefineLiteralLookup 101, 931, 'cs-CZ', N'Cmn_PersoSearchCompanyName', N'Společnost'
EXEC DefineLiteralLookup 101, 932, 'cs-CZ', N'Cmn_PersoSearchDepartment', N'Oddělení'
EXEC DefineLiteralLookup 101, 933, 'cs-CZ', N'Cmn_Predistributed', N'Přímá volba agenta'

EXEC DefineLiteralLookup 101, 950, 'cs-CZ', N'Rec_Direction', N'Směr'
EXEC DefineLiteralLookup 101, 951, 'cs-CZ', N'Rec_StartTime', N'Čas nahrávky'
EXEC DefineLiteralLookup 101, 952, 'cs-CZ', N'Rec_LocalNumber', N'Místní číslo'
EXEC DefineLiteralLookup 101, 953, 'cs-CZ', N'Rec_RemoteNumber', N'Číslo protistrany'
EXEC DefineLiteralLookup 101, 954, 'cs-CZ', N'Rec_Duration', N'Délka nahrávky'
EXEC DefineLiteralLookup 101, 955, 'cs-CZ', N'Rec_StateInfo', N'Doplňková informace'
EXEC DefineLiteralLookup 101, 956, 'cs-CZ', N'Rec_Direction_I', N'Příchozí'
EXEC DefineLiteralLookup 101, 957, 'cs-CZ', N'Rec_Direction_O', N'Odchozí'
EXEC DefineLiteralLookup 101, 958, 'cs-CZ', N'Rec_NoRecords', N'K hovoru nejsou žádné nahrávky'
EXEC DefineLiteralLookup 101, 959, 'cs-CZ', N'Rec_LinkLabel', N'Stáhnout nebo přehrát soubor v počítači'
EXEC DefineLiteralLookup 101, 960, 'cs-CZ', N'Rec_Link', N'Stáhnout'

EXEC DefineLiteralLookup 101, 980, 'cs-CZ', N'Hist_Loading', N'Načítám historii ...'
EXEC DefineLiteralLookup 101, 981, 'cs-CZ', N'Hist_TimeLocal', N'Čas'
EXEC DefineLiteralLookup 101, 982, 'cs-CZ', N'Hist_EventType', N'Událost'

EXEC DefineLiteralLookup 101, 990, 'cs-CZ', N'Frm_IntegerRange', N'Číslo musí být v rozsahu: '

EXEC DefineLiteralLookup 101, 800, 'cs-CZ', N'Dqg_RowEntry', N'Klikněte a zadejte řádek, na který se má přejít.'
EXEC DefineLiteralLookup 101, 801, 'cs-CZ', N'Dqg_Ascending', N'vzestupně'
EXEC DefineLiteralLookup 101, 802, 'cs-CZ', N'Dqg_Descending', N'sestupně'
EXEC DefineLiteralLookup 101, 803, 'cs-CZ', N'Dqg_FilterTextTip', N'Filtr textový abc, abc*, *abc'
EXEC DefineLiteralLookup 101, 804, 'cs-CZ', N'Dqg_FilterFullTextTip', N'Filtr fulltextový abc, abc*, & | &!'
EXEC DefineLiteralLookup 101, 805, 'cs-CZ', N'Dqg_FilterFreeTextTip', N'Filtr freetextový abc'
EXEC DefineLiteralLookup 101, 806, 'cs-CZ', N'Dqg_FilterOptionsTip', N'Filtr konkrétní hodnoty z výběru'
EXEC DefineLiteralLookup 101, 807, 'cs-CZ', N'Dqg_ResetFilter', N'Vymazat všechny filtry'
EXEC DefineLiteralLookup 101, 808, 'cs-CZ', N'Dqg_ResetAll', N'Vymazat všechna nastavení'
EXEC DefineLiteralLookup 101, 809, 'cs-CZ', N'Dqg_Reload', N'Načíst znovu data'
