 DECLARE @Id AS UNIQUEIDENTIFIER=(SELECT TOP 1 PathId FROM ASPNET_iCC.dbo.aspnet_Paths WHERE Path LIKE '%AdminPage8%')
 BEGIN TRANSACTION
DELETE FROM ASPNET_iCC.dbo.aspnet_PersonalizationAllUsers
WHERE PathId=@Id


DELETE FROM ASPNET_iCC.dbo.aspnet_Paths
WHERE  PathId=@Id
COMMIT TRANSACTION

--ROLLBACK TRANSACTION
