/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ContactId]
      ,[TimeUtc]
      ,[FirstName]
      ,[LastName]
      ,[CompanyName]
      ,[Department]
      ,[ParentContactId]
      ,[FormDataId]
      ,[BodyHtml]
      ,[Description]
      ,[Changed]
      ,[Correlation]
      ,[ExternalKey]
      ,[Deleted]
      ,[BlockMarketingUsage]
      ,[GdprArchived]
      ,[GdprExpired]
      ,[ArchiveAfter]
      ,[ExpireAfter]
      ,[ObliviateAfter]
      ,[GdprObliviated]
      ,[Synchronized]
      ,[ContactModelId]
  FROM [iCC].[dbo].[Contact]
  WHERE 1=1
  AND ContactId='E595CE9E-179C-4087-A6C5-00065F711501'