USE iCC
GO
/*
ALTER INDEX ALL ON [dbo].[EtlQuery] REORGANIZE
ALTER INDEX ALL ON [dbo].[PostCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[EtlStore] REORGANIZE
ALTER INDEX ALL ON [dbo].[PreCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[Gateway] REORGANIZE
ALTER INDEX ALL ON [dbo].[Predictor] REORGANIZE
ALTER INDEX ALL ON [dbo].[GatewayCondition] REORGANIZE
--ALTER INDEX ALL ON [dbo].[FSCMonitor] REORGANIZE
ALTER INDEX ALL ON [dbo].[Proficiency] REORGANIZE
ALTER INDEX ALL ON [dbo].[GdprAuthorisation] REORGANIZE
ALTER INDEX ALL ON [dbo].[Project] REORGANIZE
ALTER INDEX ALL ON [dbo].[GdprCategory] REORGANIZE
ALTER INDEX ALL ON [dbo].[ProjectCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[GdprCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[ProjectTransition] REORGANIZE
ALTER INDEX ALL ON [dbo].[GdprDeletedItem] REORGANIZE
--ALTER INDEX ALL ON [dbo].[HolidayPlan] REORGANIZE
ALTER INDEX ALL ON [dbo].[Queue] REORGANIZE
ALTER INDEX ALL ON [dbo].[GdprEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[QuotaCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[GdprEvidence] REORGANIZE
ALTER INDEX ALL ON [dbo].[QuotaExpression] REORGANIZE
ALTER INDEX ALL ON [dbo].[GdprLegalisation] REORGANIZE
ALTER INDEX ALL ON [dbo].[Redirector] REORGANIZE
ALTER INDEX ALL ON [dbo].[GdprPurpose] REORGANIZE
ALTER INDEX ALL ON [dbo].[Rep_Date] REORGANIZE
ALTER INDEX ALL ON [dbo].[GdprSensitivity] REORGANIZE
ALTER INDEX ALL ON [dbo].[Rep_Time] REORGANIZE
ALTER INDEX ALL ON [dbo].[Holiday] REORGANIZE
ALTER INDEX ALL ON [dbo].[Role] REORGANIZE
ALTER INDEX ALL ON [dbo].[ChangeRequest] REORGANIZE
ALTER INDEX ALL ON [dbo].[Scale] REORGANIZE
ALTER INDEX ALL ON [dbo].[Chat] REORGANIZE
ALTER INDEX ALL ON [dbo].[Scenario] REORGANIZE
ALTER INDEX ALL ON [dbo].[ChatEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[ScenarioCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[ChatGateCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[ScenarioConsolidation] REORGANIZE
ALTER INDEX ALL ON [dbo].[ChatGateway] REORGANIZE
ALTER INDEX ALL ON [dbo].[ScenarioResult] REORGANIZE
ALTER INDEX ALL ON [dbo].[ChatProjectCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[ScenarioResultEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[IdmAccount] REORGANIZE
ALTER INDEX ALL ON [dbo].[ScenarioResultValue] REORGANIZE
ALTER INDEX ALL ON [dbo].[IdmMap] REORGANIZE
ALTER INDEX ALL ON [dbo].[Scope] REORGANIZE
ALTER INDEX ALL ON [dbo].[IdmRule] REORGANIZE
ALTER INDEX ALL ON [dbo].[ActionTrigger] REORGANIZE
ALTER INDEX ALL ON [dbo].[Screen] REORGANIZE
ALTER INDEX ALL ON [dbo].[ImrScript] REORGANIZE
ALTER INDEX ALL ON [dbo].[Agent] REORGANIZE
ALTER INDEX ALL ON [dbo].[ScreenControl] REORGANIZE
ALTER INDEX ALL ON [dbo].[ImrStep] REORGANIZE
ALTER INDEX ALL ON [dbo].[AgentEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[ScreenControlParameter] REORGANIZE
ALTER INDEX ALL ON [dbo].[InboundCall] REORGANIZE
ALTER INDEX ALL ON [dbo].[Announcement] REORGANIZE
ALTER INDEX ALL ON [dbo].[Script] REORGANIZE
ALTER INDEX ALL ON [dbo].[Issue] REORGANIZE
ALTER INDEX ALL ON [dbo].[Attachment] REORGANIZE
ALTER INDEX ALL ON [dbo].[ScriptStep] REORGANIZE
ALTER INDEX ALL ON [dbo].[IssueCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[BulkMessage] REORGANIZE
ALTER INDEX ALL ON [dbo].[Seating] REORGANIZE
ALTER INDEX ALL ON [dbo].[IssueEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[BulkMessageImport] REORGANIZE
ALTER INDEX ALL ON [dbo].[SecurityEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[IvrEntry] REORGANIZE
ALTER INDEX ALL ON [dbo].[BusyCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[SchedulePostCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[IvrScript] REORGANIZE
ALTER INDEX ALL ON [dbo].[BusyConditionRule] REORGANIZE
ALTER INDEX ALL ON [dbo].[Skill] REORGANIZE
ALTER INDEX ALL ON [dbo].[IvrStep] REORGANIZE
ALTER INDEX ALL ON [dbo].[CallEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[Status] REORGANIZE
ALTER INDEX ALL ON [dbo].[KbArticle] REORGANIZE
ALTER INDEX ALL ON [dbo].[CallRecord] REORGANIZE
ALTER INDEX ALL ON [dbo].[SubTopic] REORGANIZE
ALTER INDEX ALL ON [dbo].[KbArticleTag] REORGANIZE
ALTER INDEX ALL ON [dbo].[CallResultDetail] REORGANIZE
ALTER INDEX ALL ON [dbo].[TextMatch] REORGANIZE
ALTER INDEX ALL ON [dbo].[KbEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[Campaign] REORGANIZE
ALTER INDEX ALL ON [dbo].[TextMatchRule] REORGANIZE
ALTER INDEX ALL ON [dbo].[KbTag] REORGANIZE
ALTER INDEX ALL ON [dbo].[CampaignImport] REORGANIZE
ALTER INDEX ALL ON [dbo].[Topic] REORGANIZE
ALTER INDEX ALL ON [dbo].[Language] REORGANIZE
ALTER INDEX ALL ON [dbo].[ClientAlert] REORGANIZE
ALTER INDEX ALL ON [dbo].[Traffic] REORGANIZE
ALTER INDEX ALL ON [dbo].[LiteralLookup] REORGANIZE
ALTER INDEX ALL ON [dbo].[ClientAlertComposition] REORGANIZE
ALTER INDEX ALL ON [dbo].[TrafficSlot] REORGANIZE
ALTER INDEX ALL ON [dbo].[MediaReduction] REORGANIZE
ALTER INDEX ALL ON [dbo].[ClientAlertEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[TtsCache] REORGANIZE
ALTER INDEX ALL ON [dbo].[Message] REORGANIZE
ALTER INDEX ALL ON [dbo].[Configuration] REORGANIZE
ALTER INDEX ALL ON [dbo].[VoiceMailBox] REORGANIZE
ALTER INDEX ALL ON [dbo].[MessageEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[Contact] REORGANIZE
ALTER INDEX ALL ON [dbo].[VoiceMailMessage] REORGANIZE
ALTER INDEX ALL ON [dbo].[MessagePostCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[ContactComposition] REORGANIZE
ALTER INDEX ALL ON [dbo].[WaitingQueue] REORGANIZE
ALTER INDEX ALL ON [dbo].[MessagePreCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[ContactEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[WaitPostCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[MessageProjectCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[ContactModel] REORGANIZE
ALTER INDEX ALL ON [dbo].[WebAdminEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[MessageScheduleCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[Content] REORGANIZE
ALTER INDEX ALL ON [dbo].[WebAdminMenu] REORGANIZE
ALTER INDEX ALL ON [dbo].[MessageWaitPostCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[ContentCondition] REORGANIZE
ALTER INDEX ALL ON [dbo].[WebSiteEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[Navigation] REORGANIZE
ALTER INDEX ALL ON [dbo].[Correlation] REORGANIZE
ALTER INDEX ALL ON [dbo].[WebSiteRouting] REORGANIZE
ALTER INDEX ALL ON [dbo].[Numbering] REORGANIZE
ALTER INDEX ALL ON [dbo].[Crew] REORGANIZE
ALTER INDEX ALL ON [dbo].[WebSiteTemplate] REORGANIZE
ALTER INDEX ALL ON [dbo].[OfficePlan] REORGANIZE
ALTER INDEX ALL ON [dbo].[CrewMember] REORGANIZE
ALTER INDEX ALL ON [dbo].[WfmActivity] REORGANIZE
ALTER INDEX ALL ON [dbo].[OfficeSlot] REORGANIZE
ALTER INDEX ALL ON [dbo].[DataQuery] REORGANIZE
ALTER INDEX ALL ON [dbo].[WfmAgent] REORGANIZE
ALTER INDEX ALL ON [dbo].[OutboundCall] REORGANIZE
ALTER INDEX ALL ON [dbo].[DataQueryColumn] REORGANIZE
ALTER INDEX ALL ON [dbo].[WfmEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[OutboundList] REORGANIZE
ALTER INDEX ALL ON [dbo].[DataQueryEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[WfmHoliday] REORGANIZE
ALTER INDEX ALL ON [dbo].[OutboundListImport] REORGANIZE
ALTER INDEX ALL ON [dbo].[DataQuerySource] REORGANIZE
ALTER INDEX ALL ON [dbo].[WfmPlan] REORGANIZE
ALTER INDEX ALL ON [dbo].[Paging] REORGANIZE
ALTER INDEX ALL ON [dbo].[Device] REORGANIZE
ALTER INDEX ALL ON [dbo].[WfmPlanError] REORGANIZE
ALTER INDEX ALL ON [dbo].[PagingEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[DirectEditTable] REORGANIZE
ALTER INDEX ALL ON [dbo].[WfmPlanMember] REORGANIZE
ALTER INDEX ALL ON [dbo].[PagingMember] REORGANIZE
ALTER INDEX ALL ON [dbo].[Direction] REORGANIZE
ALTER INDEX ALL ON [dbo].[WfmRotation] REORGANIZE
ALTER INDEX ALL ON [dbo].[PagingRule] REORGANIZE
ALTER INDEX ALL ON [dbo].[Editor] REORGANIZE
ALTER INDEX ALL ON [dbo].[WfmRotationComposition] REORGANIZE
ALTER INDEX ALL ON [dbo].[PagingTemplate] REORGANIZE
ALTER INDEX ALL ON [dbo].[EditorTab] REORGANIZE
ALTER INDEX ALL ON [dbo].[WfmSlot] REORGANIZE
ALTER INDEX ALL ON [dbo].[Permission] REORGANIZE
ALTER INDEX ALL ON [dbo].[EditorTask] REORGANIZE
ALTER INDEX ALL ON [dbo].[Workflow] REORGANIZE
ALTER INDEX ALL ON [dbo].[Perso] REORGANIZE
ALTER INDEX ALL ON [dbo].[EtlCube] REORGANIZE
ALTER INDEX ALL ON [dbo].[WorkflowEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[Phase] REORGANIZE
ALTER INDEX ALL ON [dbo].[EtlDimGen] REORGANIZE
ALTER INDEX ALL ON [dbo].[WorkflowInstance] REORGANIZE
ALTER INDEX ALL ON [dbo].[PhaseTransition] REORGANIZE
ALTER INDEX ALL ON [dbo].[EtlDimSource] REORGANIZE
ALTER INDEX ALL ON [dbo].[WorkflowStep] REORGANIZE
ALTER INDEX ALL ON [dbo].[PhoneBook] REORGANIZE
ALTER INDEX ALL ON [dbo].[EtlExport] REORGANIZE
ALTER INDEX ALL ON [dbo].[Workplace] REORGANIZE
ALTER INDEX ALL ON [dbo].[PhoneComposition] REORGANIZE
ALTER INDEX ALL ON [dbo].[EtlFactColumn] REORGANIZE
ALTER INDEX ALL ON [dbo].[PhoneNumber] REORGANIZE
ALTER INDEX ALL ON [dbo].[EtlFactSource] REORGANIZE
ALTER INDEX ALL ON [dbo].[PhoneNumberEvent] REORGANIZE
ALTER INDEX ALL ON [dbo].[EtlFilter] REORGANIZE
ALTER INDEX ALL ON [dbo].[Pilot] REORGANIZE
ALTER INDEX ALL ON [dbo].[EtlPickItem] REORGANIZE
ALTER INDEX ALL ON [dbo].[Portal] REORGANIZE
*/

   DECLARE @tableSchema varchar(max), 
        @tableName varchar(max),
        @tsql nvarchar(max);

DECLARE cur CURSOR FOR SELECT TABLE_SCHEMA, TABLE_NAME FROM Information_Schema.tables where  table_type ='BASE TABLE'

OPEN cur 

FETCH NEXT FROM cur into @tableSchema, @tableName

WHILE @@FETCH_STATUS = 0 
BEGIN
    SET @tsql ='ALTER INDEX ALL ON [' + @tableSchema + '].[' + @tableName + '] REORGANIZE'
    PRINT(@tsql)
    EXEC SP_EXECUTESQL @tsql;
FETCH NEXT FROM cur into @tableSchema, @tableName
END

CLOSE cur
DEALLOCATE cur