BACKUP DATABASE [iCC] TO  DISK = N'nul' WITH NOFORMAT, INIT,  NAME = N'iCC-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
 
BACKUP LOG iCC TO DISK= N'nul'
GO
 
USE [iCC]
GO
DBCC SHRINKFILE (N'iCC_log' , 0, TRUNCATEONLY)
GO

