DECLARE @Id AS UNIQUEIDENTIFIER='22669630-84AA-49FC-9868-96DEE92E5B55'
 BEGIN TRANSACTION
UPDATE [SRec].[dbo].[ScreenRecord]
SET  AgentName = 'CDZAP\krncan'
WHERE  (AgentName = 'CDGR\krncan')

COMMIT TRANSACTION

--ROLLBACK TRANSACTION
