/* Portal_SupervisorPage: Všechny zprávy e-mailové fronty */
INSERT [DataQuery] ([DataQueryId], [DisplayName], [Description], [QueryGroup], [QuerySortExpression], [QueryText], [ManualFilter], [SnapshotInterval], [CacheInterval], [TimeLine], [Deleted])
 VALUES(N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Všechny zprávy e-mailové fronty',NULL,N'Portal_SupervisorPage',N'TimeUtc DESC',N'SELECT  DISTINCT
c.Description,m.MessageId, M.TimeUtc, M.MessageType, M.MessagePhase, M.Direction, M.RemoteAddress, 
M.FromField, M.ToField, M.ToCcField, M.SubjectField, ISNULL(M.BodyText, M.BodyHtml) as BodyField,
M.ProjectId, M.GatewayId, M.AgentId, M.TeamName,
 M.LanguageId, P.DisplayName AS ProjectName, G.DisplayName AS GatewayName, A.DisplayName AS AgentName, L.DisplayName AS LanguageName,
ISNULL(ReceivedSentTime,DraftTime) AS MessageTime,
CAST(CASE WHEN MessageResult=''Active'' THEN 1 ELSE 0 END AS bit) AS IsActive,
CAST(CASE WHEN MessagePhase=''Draft'' OR MessagePhase=''Received'' THEN 1 ELSE 0 END AS bit) AS IsNew,
CAST(CASE WHEN (MessagePhase=''Read'' OR MessagePhase=''Received'') AND ReceivedSentTime<getdate() THEN 1 ELSE 0 END AS bit) AS IsLate,
CAST(CASE WHEN EXISTS(SELECT * From Attachment WHERE M.MessageId=Attachment.MessageId) THEN 1 ELSE 0 END AS bit) AS HasAttachment

FROM Message AS M 
LEFT JOIN Project AS P ON M.ProjectId=P.ProjectId
LEFT JOIN Gateway AS G ON M.GatewayId=G.GatewayId
LEFT JOIN Agent AS A ON M.AgentId=A.AgentId
LEFT JOIN Language AS L ON M.LanguageId=L.LanguageId
/*LEFT JOIN ScenarioResult AS SR WITH(NOLOCK) ON SR.MessageId=M.MessageId */
LEFT JOIN Contact as C with (NOLOCK) on c.Contactid=m.ContactId
WHERE (MessageType =''Email'' AND M.AGENTID IS NULL AND M.DIRECTION =''I'' AND MessagePhase <> ''Canceled'' and @SubjectField=''##FullText##'' and @FromField=''##FullText##'' and @ToField=''##FullText##'' and @BodyField=''##FullText##'')and (m.spamlevel is null or m.spamlevel = 0) and m.messageResult<>''Closed'' 
and  m.GatewayId<>''656bb249-7e33-48d9-ad41-cca8bdacfefc''
',0,NULL,NULL,NULL,0)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'535eeae8-ae05-4c71-b9db-a450b3311fe1',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Výběr',N'Toggle',N'MessageId',NULL,NULL,N'~/CustomImages/Bullet-{0}.png',NULL,NULL,NULL,NULL,0,30,1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'a0e384a4-7974-492a-a89e-d5658a568f5a',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Typ',N'Image',N'MessageType',N'~/CustomImages/{0}.png',N'MessageId',N'/ReactClient/Pages/MessageEditor.html?Id={0}',NULL,N'MessageType',N'MessageType',NULL,0,25,5,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'df3ca555-72ca-4d3b-a2eb-1e5ace78fbed',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Směr',N'Image',N'Direction',N'~/CustomImages/Dir-{0}.png',NULL,NULL,NULL,N'MessageDirection',N'Direction',NULL,0,25,7,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'917ca3ad-b503-48ea-a54a-189df1e97653',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Příl.',N'Image',N'HasAttachment',N'~/CustomImages/Att-{0}.png',NULL,NULL,NULL,N'Bool',N'HasAttachment',NULL,0,25,8,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'02fa9089-16b0-4d1d-ac2d-07969156c502',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Čas',N'DateTimeFromTo',N'MessageTime',N'{0:dd.MM HH.mm}',NULL,NULL,NULL,NULL,N'MessageTime',NULL,0,60,10,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'3287d310-f4ac-4b73-be20-0243c007a077',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Od',N'HyperFullText',N'FromField',NULL,N'MessageId',N'/ReactClient/Pages/MessageEditor.html?Id={0}',N'FromField',NULL,N'FromField',NULL,0,120,20,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'867a3dee-a515-4bfa-af87-6182fa062fa8',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Předmět',N'HyperFullText',N'SubjectField',NULL,N'MessageId',N'/ReactClient/Pages/MessageEditor.html?Id={0}',N'SubjectField',NULL,N'SubjectField',NULL,0,220,30,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'c16c20f0-be11-4375-8ae2-200bef8b23dd',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Komu',N'HyperFullText',N'ToField',NULL,N'MessageId',N'/ReactClient/Pages/MessageEditor.html?Id={0}',N'ToField',NULL,N'ToField',NULL,0,125,40,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'33c3682f-491a-4524-a08b-9e70520cf36d',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Stav',N'Select',N'MessagePhase',NULL,NULL,NULL,NULL,N'MessagePhase',N'MessagePhase',NULL,0,60,50,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'76fba989-c45a-4737-ab14-fbf2a0dbcbf2',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Agent',N'Text',N'AgentName',NULL,NULL,NULL,N'AgentId',N'AgentName',N'AgentName',NULL,0,80,60,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'17572c9f-2c8e-4678-9fb0-6e23c0964b8d',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Tým',N'Text',N'TeamName',NULL,NULL,NULL,NULL,NULL,N'TeamName',NULL,0,80,61,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'214f222e-434c-4460-a0ed-66a2e6793d7e',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Projekt',N'ForeignKey',N'ProjectName',NULL,NULL,NULL,N'ProjectId',N'ProjectName',N'ProjectName',NULL,0,100,70,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'0916fe44-88be-4474-b5ea-a3d2c04a35b9',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Text zprávy',N'HyperFullText',N'BodyField',NULL,N'MessageId',N'/ReactClient/Pages/MessageEditor.html?Id={0}',N'M.*',NULL,N'BodyField',NULL,0,140,80,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'daa0a295-f6be-4ee3-aa5c-511a5ee1c3a8',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Kopie',N'Text',N'ToCcField',NULL,NULL,NULL,NULL,NULL,N'ToCcField',NULL,0,80,85,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'67ccd2cc-892e-43cd-a4cb-93b71bd27f91',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Nová zpráva',N'Bold',N'IsNew',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,91,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'1d63d61e-b2c6-41ef-b76b-79b4156c7a1f',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Stará 1D',N'Color',N'IsLate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,92,N'#FFE9D1',0,NULL,N'warning',NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'3ad17d95-50e7-46e6-87b9-d2d000fda359',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Aktivní',N'Color',N'IsActive',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,93,N'#CCFADF',0,NULL,N'success',NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'50c26fc3-a3ac-4950-9f32-07c175a6733e',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Adresa',N'HyperLink',N'RemoteAddress',NULL,N'MessageId',N'/ReactClient/Pages/MessageEditor.html?Id={0}',NULL,NULL,N'RemoteAddress',NULL,0,280,150,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat])
 VALUES (N'3811dec8-1da5-470d-8454-2edc6f3bfb43',N'4936804c-9020-4521-ae03-f78c75ecbddf',N'Brána',N'ForeignKey',N'GatewayName',NULL,NULL,NULL,N'GatewayId',N'GatewayName',N'GatewayName',NULL,0,80,160,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)

