/* Sup_Portal: Všechny šablony */
INSERT [DataQuery] ([DataQueryId], [DisplayName], [Description], [QueryGroup], [QuerySortExpression], [QueryText], [ManualFilter], [SnapshotInterval], [CacheInterval], [TimeLine], [Deleted], [LogLevel])
 VALUES(N'85a44403-822d-43f4-afdb-08a9783cb033',N'Všechny šablony',N'DPD',N'Sup_Portal',N'GroupName',N'SELECT M.MessageId, M.MessageType, M.DraftTime, dbo.FirstPart(M.SubjectField,'':'') as GroupName, dbo.LastPart(M.SubjectField,'':'') as TmpName, 
M.AgentId, M.GatewayId, M.ProjectId, M.LanguageId, M.TeamName,
P.DisplayName AS ProjectName, A.DisplayName AS AgentName, L.DisplayName AS LanguageName,
CAST(CASE WHEN M.AgentId=@MeAgentid THEN 1 ELSE 0 END AS bit) AS IsMy,
G.DisplayName as GatewayName
FROM Message AS M
LEFT JOIN Project AS P ON M.ProjectId=P.ProjectId
LEFT JOIN Agent AS A ON M.AgentId=A.AgentId
LEFT JOIN Language AS L ON M.LanguageId=L.LanguageId
LEFT JOIN Gateway AS G ON M.GatewayId=G.GatewayId
WHERE MessageType Like ''Tmp%'' AND MessageResult = ''Active''',0,NULL,NULL,NULL,0,0)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity], [DisplayGlyph])
 VALUES (N'6442712b-a0c1-4b78-a881-305401e1c621',N'85a44403-822d-43f4-afdb-08a9783cb033',N'Typ',N'Image',N'MessageType',N'~/CustomImages/{0}.png',N'MessageId',N'/ReactClient/Pages/MessageEditor.html?Id={0}',NULL,N'MessageType',N'MessageType',NULL,0,20,5,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity], [DisplayGlyph])
 VALUES (N'6457e1c4-89e3-40a0-b925-f885292c86b0',N'85a44403-822d-43f4-afdb-08a9783cb033',N'Čas',N'DateTimeFromTo',N'DraftTime',N'{0:dd.MM.yy HH.mm}',NULL,NULL,NULL,NULL,N'DraftTime',NULL,0,80,10,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity], [DisplayGlyph])
 VALUES (N'6d9d3433-60ef-4fd5-a765-9b02370c767f',N'85a44403-822d-43f4-afdb-08a9783cb033',N'Skupina',N'Select',N'GroupName',NULL,NULL,NULL,NULL,NULL,N'GroupName',NULL,0,70,20,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity], [DisplayGlyph])
 VALUES (N'eef5ab6a-7b6a-4ae7-87fb-14b153531bf6',N'85a44403-822d-43f4-afdb-08a9783cb033',N'Předmět',N'HyperLink',N'TmpName',NULL,N'MessageId',N'/ReactClient/Pages/MessageEditor.html?Id={0}',NULL,NULL,N'TmpName',NULL,0,220,30,NULL,0,NULL,NULL,500,NULL,NULL,NULL, NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity], [DisplayGlyph])
 VALUES (N'b86a1d0f-3c96-4d86-858f-fb5f1bf4b1f8',N'85a44403-822d-43f4-afdb-08a9783cb033',N'$Cmn_Agent',N'ForeignKey',N'AgentName',NULL,NULL,NULL,N'AgentId',N'AgentName',N'AgentName',NULL,0,80,60,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity], [DisplayGlyph])
 VALUES (N'ed3b56a9-f273-4b7f-ae59-258a8be6d559',N'85a44403-822d-43f4-afdb-08a9783cb033',N'Tým',N'Text',N'TeamName',NULL,NULL,NULL,NULL,NULL,N'TeamName',NULL,0,80,61,NULL,0,NULL,NULL,500,NULL,NULL,NULL, NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity], [DisplayGlyph])
 VALUES (N'e2f6df08-d993-43ac-b897-ad6673b53451',N'85a44403-822d-43f4-afdb-08a9783cb033',N'Brána',N'Text',N'GatewayName',NULL,NULL,NULL,NULL,NULL,N'GatewayName',NULL,0,120,65,NULL,0,NULL,NULL,500,NULL,NULL,NULL, NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity], [DisplayGlyph])
 VALUES (N'6ef9562d-4ce8-4c97-99ac-32f552573a99',N'85a44403-822d-43f4-afdb-08a9783cb033',N'Projekt',N'ForeignKey',N'ProjectName',NULL,NULL,NULL,N'ProjectId',N'ProjectName',N'ProjectName',NULL,0,100,70,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity], [DisplayGlyph])
 VALUES (N'9ddc825a-5b55-4ea2-8981-0e8a577dd008',N'85a44403-822d-43f4-afdb-08a9783cb033',N'Jazyk',N'ForeignKey',N'LanguageName',NULL,NULL,NULL,N'LanguageId',N'LanguageName',N'LanguageName',NULL,0,60,71,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity], [DisplayGlyph])
 VALUES (N'4e6e1ec5-113d-49e3-b481-e977261fef1e',N'85a44403-822d-43f4-afdb-08a9783cb033',N'Moje ?',N'Bold',N'IsMy',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,91,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity], [DisplayGlyph])
 VALUES (N'ab0b44f5-673f-4b20-81f9-cd25cd8d6fec',N'85a44403-822d-43f4-afdb-08a9783cb033',N'Id šablony',N'Text',N'MessageId',NULL,NULL,NULL,NULL,NULL,N'MessageId',NULL,0,230,100,NULL,0,NULL,NULL,500,NULL,NULL,NULL, NULL, NULL)

