/* AgentPage SK: Všetky správy */
INSERT [DataQuery] ([DataQueryId], [DisplayName], [Description], [QueryGroup], [QuerySortExpression], [QueryText], [ManualFilter], [SnapshotInterval], [CacheInterval], [TimeLine], [Deleted], [LogLevel])
 VALUES(N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Všetky správy',N'Message',N'AgentPage SK',N'TimeUtc DESC',N'SELECT 
M.MessageId,M.mark, M.TimeUtc, M.MessageType, M.MessagePhase, M.Direction, M.RemoteAddress, m.SignatureValidity,
M.FromField, M.ToField, M.ToCcField, M.SubjectField,
M.ProjectId, M.GatewayId,M.EndTime, M.AgentId, M.TeamName, M.LanguageId, P.DisplayName AS ProjectName, G.DisplayName AS GatewayName, A.DisplayName AS AgentName, L.DisplayName AS LanguageName, I.DisplayName
,ISNULL(ReceivedSentTime,DraftTime) AS MessageTime,
/*
,CAST(CASE WHEN MessageResult=''Active'' THEN 1 ELSE 0 END AS bit) AS IsActive,
CAST(CASE WHEN MessagePhase=''Draft'' OR MessagePhase=''Received'' THEN 1 ELSE 0 END AS bit) AS IsNew,*/
CAST(CASE WHEN M.MessageResult=''Active'' AND datediff(hour,M.ReceivedSentTime,getdate()) > 48 THEN 1 ELSE 0 END AS bit) AS IsLate
,CAST(CASE WHEN EXISTS(SELECT TOP 1 1 From Attachment WHERE M.MessageId=Attachment.MessageId) THEN 1 ELSE 0 END AS bit) AS HasAttachment
,CAST(CASE WHEN EXISTS(SELECT TOP 1 1 From Issue WHERE M.IssueId=IssueId and Activity = ''Closed'' and PhaseId = ''73aed0fe-ba97-451f-a97b-b56a9f632e72'') and M.MessageResult=''Active'' THEN 1 ELSE 0 END AS bit) AS HasResolvedBO
, LEFT(ISNULL(M.BodyText, M.BodyHtml),500) as BodyField

FROM Message AS M with(nolock)
LEFT JOIN Project AS P with(nolock) ON M.ProjectId=P.ProjectId
LEFT JOIN Gateway AS G with(nolock) ON M.GatewayId=G.GatewayId
LEFT JOIN Agent AS A with(nolock) ON M.AgentId=A.AgentId
LEFT JOIN Language AS L with(nolock) ON M.LanguageId=L.LanguageId
LEFT JOIN Issue as I with(nolock) on M.IssueId = I.IssueId
WHERE (MessageType =''Email'' and @SubjectField=''##FullText##'' and @FromField=''##FullText##'' and @ToField=''##FullText##'') and @BodyField=''##FullText##'' and 
(m.spamlevel is null or m.spamlevel = 0) and m.messagephase != ''Canceled''
and NOT(m.Direction = ''O'' and m.AgentId IS NULL)',0,NULL,NULL,NULL,0,0)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'fef88652-3098-4e30-ba7b-42aa1965afda',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Typ',N'Image',N'MessageType',N'~/CustomImages/{0}.png',N'MessageId',N'/ReactClient/Pages/MessageEditor.html?Id={0}',NULL,N'MessageType',N'MessageType',NULL,0,2,5,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'14584995-8813-4851-8c40-ae74c3f1d581',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Mark',N'ImageScript',N'Mark',N'~/CustomImages/Ico12x12/Flag_{0}.png',N'MessageId',NULL,NULL,NULL,N'Mark',NULL,0,2,6,NULL,0,N'UPDATE Message SET Mark = (Mark+1) % 4 WHERE @Id=MessageId',NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'1554da06-8171-451b-afe7-c95d6a9ee590',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Smer',N'Image',N'Direction',N'~/CustomImages/Dir-{0}.png',NULL,NULL,NULL,N'MessageDirection',N'Direction',NULL,0,2,7,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'a99a2a4b-aa54-497b-8b1e-bee136bf5178',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Príl.',N'Image',N'HasAttachment',N'~/CustomImages/Att-{0}.png',NULL,NULL,NULL,N'Bool',N'HasAttachment',NULL,0,2,8,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'c0fe9164-07aa-4bdf-a7cc-d1f563070316',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Čas',N'DateTimeFromTo',N'MessageTime',N'{0:dd.MM.yy HH.mm}',NULL,NULL,NULL,NULL,N'MessageTime',NULL,0,6,10,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'd75abee9-6f72-41a5-b04e-ace0d7995891',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Stav',N'Select',N'MessagePhase',NULL,NULL,NULL,NULL,N'MessagePhase',N'MessagePhase',NULL,0,4,15,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'e6f0ffdb-e665-427c-a6e5-f1838f6fda1d',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Č. prípadu',N'Text',N'DisplayName',NULL,NULL,NULL,NULL,NULL,N'DisplayName',NULL,0,4,18,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'2c471f9f-1644-4b9c-af8c-919b62e12459',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Agent',N'Select',N'AgentName',NULL,NULL,NULL,NULL,NULL,N'AgentName',NULL,0,9,20,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'49edd888-0f6e-416c-aa58-c5a33c48957b',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Adresa',N'Text',N'RemoteAddress',NULL,NULL,NULL,NULL,NULL,N'RemoteAddress',NULL,0,11,25,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'6c4520e0-94c5-4e18-8313-750de1b89801',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Komu',N'FullText',N'ToField',NULL,NULL,NULL,N'ToField',NULL,N'ToField',NULL,0,7,27,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'db3da6cd-043d-4e63-b0c9-1e3edb99aea8',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Predmet',N'HyperFullText',N'SubjectField',NULL,N'MessageId',N'/ReactClient/Pages/MessageEditor.html?Id={0}',N'SubjectField',NULL,N'SubjectField',NULL,0,15,30,NULL,0,NULL,NULL,500,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'27e72245-8e0b-4f90-adc0-6a23b51c85da',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Telo správy',N'HyperFullText',N'BodyField',NULL,N'MessageId',N'/ReactClient/Pages/MessageEditor.html?Id={0}',N'M.*',NULL,N'BodyField',NULL,0,40,40,NULL,0,NULL,NULL,500,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'fa5ac1b4-86f6-4a8c-bb36-605a7bfd556b',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Stará 2D',N'Color',N'IsLate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,280,NULL,0,NULL,N'danger',NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'28143018-6d36-48c4-88f4-425f998c3a40',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Od',N'FullText',N'FromField',NULL,NULL,NULL,N'FromField',NULL,N'FromField',NULL,0,NULL,400,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'122afeee-01b9-4545-b81a-0d2df3a6fad2',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'HasResolvedBO',N'Color',N'HasResolvedBO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,410,NULL,0,NULL,N'success',NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'5b1dfd66-e5a7-43b6-ba1c-f3e3302ab033',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Brána',N'Select',N'GatewayName',NULL,NULL,NULL,NULL,NULL,N'GatewayName',NULL,0,NULL,560,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'65774880-b3bc-41b2-84c2-1c52fc5edba5',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Tým',N'Text',N'TeamName',NULL,NULL,NULL,NULL,NULL,N'TeamName',NULL,0,NULL,561,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)
INSERT [DataQueryColumn] ([DataQueryColumnId], [DataQueryId], [DisplayName], [Model], [TargetColumn], [TargetFormat], [UrlColumn], [UrlFormat], [GuidColumn], [Convertor], [SortExpression], [SortExpressionDesc], [NoFilter], [Width], [Rank], [Color], [Deleted], [SqlCmd], [Css], [ToolTip], [LiteralGroup], [GlyphColumn], [GlyphFormat], [GdprSensitivity])
 VALUES (N'527828a5-7131-4759-bcff-70070abe8fb8',N'51e35ccf-aaf3-4359-9fa8-ae5cdae1a082',N'Projekt',N'Select',N'ProjectName',NULL,NULL,NULL,NULL,NULL,N'ProjectName',NULL,0,NULL,570,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL, NULL)

